package nl.devoorkant.sbdr.cir.data.model;
// Generated Apr 14, 2016 7:26:47 PM by Hibernate Tools 3.2.4.GA



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * Applicatie generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="CirApplicatie")
@Table(name="Applicatie"
)
public class Applicatie  implements java.io.Serializable {


     private Integer applicatieId;
     private short databaseVersie;
     private short databaseRelease;
     private short databaseFix;
     private Date datum;

    public Applicatie() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Applicatie_ID", unique=true, nullable=false)
    public Integer getApplicatieId() {
        return this.applicatieId;
    }
    
    public void setApplicatieId(Integer applicatieId) {
        this.applicatieId = applicatieId;
    }


    
    @Column(name="DatabaseVersie", nullable=false)
    public short getDatabaseVersie() {
        return this.databaseVersie;
    }
    
    public void setDatabaseVersie(short databaseVersie) {
        this.databaseVersie = databaseVersie;
    }


    
    @Column(name="DatabaseRelease", nullable=false)
    public short getDatabaseRelease() {
        return this.databaseRelease;
    }
    
    public void setDatabaseRelease(short databaseRelease) {
        this.databaseRelease = databaseRelease;
    }


    
    @Column(name="DatabaseFix", nullable=false)
    public short getDatabaseFix() {
        return this.databaseFix;
    }
    
    public void setDatabaseFix(short databaseFix) {
        this.databaseFix = databaseFix;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.DATE)
    @Column(name="Datum", nullable=false, length=10)
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }





}


