package nl.devoorkant.sbdr.cir.data.model;
// Generated Apr 14, 2016 7:26:47 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * CirAansturing generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="CirCirAansturing")
@Table(name="Cir_Aansturing"
)
public class CirAansturing  implements java.io.Serializable {


     private String code;
     private Date tijdLaatsteSynchronizatie;
     private String gebruikersNaam;
     private String wachtwoord;

    public CirAansturing() {
    }

   
     @Id 

    
    @Column(name="Code", unique=true, nullable=false, length=3)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TijdLaatsteSynchronizatie", length=19)
    public Date getTijdLaatsteSynchronizatie() {
        return this.tijdLaatsteSynchronizatie;
    }
    
    public void setTijdLaatsteSynchronizatie(Date tijdLaatsteSynchronizatie) {
        this.tijdLaatsteSynchronizatie = tijdLaatsteSynchronizatie;
    }


    
    @Column(name="GebruikersNaam", nullable=false, length=50)
    public String getGebruikersNaam() {
        return this.gebruikersNaam;
    }
    
    public void setGebruikersNaam(String gebruikersNaam) {
        this.gebruikersNaam = gebruikersNaam;
    }


    
    @Column(name="Wachtwoord", nullable=false, length=40)
    public String getWachtwoord() {
        return this.wachtwoord;
    }
    
    public void setWachtwoord(String wachtwoord) {
        this.wachtwoord = wachtwoord;
    }





}


