package nl.devoorkant.sbdr.cir.data.model;
// Generated Apr 14, 2016 7:26:47 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * CirInsolventie generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="CirCirInsolventie")
@Table(name="Cir_Insolventie"
)
public class CirInsolventie  implements java.io.Serializable {


     private Integer id;
     private CirPersoon cirPersoon;
     private String nummerInsolventie;
     private String nummerSchuldSaneringsRegeling;
     private String nummerInsolventiePreHgk;
     private String codeBehandelendeInstantie;
     private String naamBehandelendeInstantie;
     private String codeBehandelendeVestiging;
     private String naamBehandelendeVestiging;
     private boolean indPreHgkgepubliceerd;
     private String rechterCommisaris;
     private String rechterCommisarisVorige;
     private String nummerInsolventieVorig;
     private boolean indGeheimAdres;
     private Date datumEindeVindbaarheid;
     private Boolean indInstroomAchterstand;
     private Set<CirHandelsnaam> cirHandelsnaams = new HashSet<CirHandelsnaam>(0);
     private Set<CirCbv> cirCbvs = new HashSet<CirCbv>(0);
     private Set<CirAdres> cirAdreses = new HashSet<CirAdres>(0);
     private Set<CirPublicatie> cirPublicaties = new HashSet<CirPublicatie>(0);

    public CirInsolventie() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Persoon_ID", nullable=false)
    public CirPersoon getCirPersoon() {
        return this.cirPersoon;
    }
    
    public void setCirPersoon(CirPersoon cirPersoon) {
        this.cirPersoon = cirPersoon;
    }



    @Transient
    public Integer getCirPersoonId() {
        return this.cirPersoon == null ? null : this.cirPersoon.getId();
    }

    public void setCirPersoonId(Integer id) {
        if (id == null) {
            this.cirPersoon = null;
        } else {
            CirPersoon obj = new CirPersoon();
            obj.setId(id);
            this.cirPersoon = obj;
        }
    }


    
    @Column(name="NummerInsolventie", nullable=false, length=40)
    public String getNummerInsolventie() {
        return this.nummerInsolventie;
    }
    
    public void setNummerInsolventie(String nummerInsolventie) {
        this.nummerInsolventie = nummerInsolventie;
    }


    
    @Column(name="NummerSchuldSaneringsRegeling", length=40)
    public String getNummerSchuldSaneringsRegeling() {
        return this.nummerSchuldSaneringsRegeling;
    }
    
    public void setNummerSchuldSaneringsRegeling(String nummerSchuldSaneringsRegeling) {
        this.nummerSchuldSaneringsRegeling = nummerSchuldSaneringsRegeling;
    }


    
    @Column(name="NummerInsolventiePreHGK", length=40)
    public String getNummerInsolventiePreHgk() {
        return this.nummerInsolventiePreHgk;
    }
    
    public void setNummerInsolventiePreHgk(String nummerInsolventiePreHgk) {
        this.nummerInsolventiePreHgk = nummerInsolventiePreHgk;
    }


    
    @Column(name="CodeBehandelendeInstantie", nullable=false, length=40)
    public String getCodeBehandelendeInstantie() {
        return this.codeBehandelendeInstantie;
    }
    
    public void setCodeBehandelendeInstantie(String codeBehandelendeInstantie) {
        this.codeBehandelendeInstantie = codeBehandelendeInstantie;
    }


    
    @Column(name="NaamBehandelendeInstantie", nullable=false, length=40)
    public String getNaamBehandelendeInstantie() {
        return this.naamBehandelendeInstantie;
    }
    
    public void setNaamBehandelendeInstantie(String naamBehandelendeInstantie) {
        this.naamBehandelendeInstantie = naamBehandelendeInstantie;
    }


    
    @Column(name="CodeBehandelendeVestiging", nullable=false, length=40)
    public String getCodeBehandelendeVestiging() {
        return this.codeBehandelendeVestiging;
    }
    
    public void setCodeBehandelendeVestiging(String codeBehandelendeVestiging) {
        this.codeBehandelendeVestiging = codeBehandelendeVestiging;
    }


    
    @Column(name="NaamBehandelendeVestiging", nullable=false, length=40)
    public String getNaamBehandelendeVestiging() {
        return this.naamBehandelendeVestiging;
    }
    
    public void setNaamBehandelendeVestiging(String naamBehandelendeVestiging) {
        this.naamBehandelendeVestiging = naamBehandelendeVestiging;
    }


    
    @Column(name="IndPreHGKGepubliceerd", nullable=false)
    public boolean isIndPreHgkgepubliceerd() {
        return this.indPreHgkgepubliceerd;
    }
    
    public void setIndPreHgkgepubliceerd(boolean indPreHgkgepubliceerd) {
        this.indPreHgkgepubliceerd = indPreHgkgepubliceerd;
    }


    
    @Column(name="RechterCommisaris", length=200)
    public String getRechterCommisaris() {
        return this.rechterCommisaris;
    }
    
    public void setRechterCommisaris(String rechterCommisaris) {
        this.rechterCommisaris = rechterCommisaris;
    }


    
    @Column(name="RechterCommisarisVorige", length=200)
    public String getRechterCommisarisVorige() {
        return this.rechterCommisarisVorige;
    }
    
    public void setRechterCommisarisVorige(String rechterCommisarisVorige) {
        this.rechterCommisarisVorige = rechterCommisarisVorige;
    }


    
    @Column(name="NummerInsolventieVorig", length=40)
    public String getNummerInsolventieVorig() {
        return this.nummerInsolventieVorig;
    }
    
    public void setNummerInsolventieVorig(String nummerInsolventieVorig) {
        this.nummerInsolventieVorig = nummerInsolventieVorig;
    }


    
    @Column(name="IndGeheimAdres", nullable=false)
    public boolean isIndGeheimAdres() {
        return this.indGeheimAdres;
    }
    
    public void setIndGeheimAdres(boolean indGeheimAdres) {
        this.indGeheimAdres = indGeheimAdres;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.DATE)
    @Column(name="DatumEindeVindbaarheid", length=10)
    public Date getDatumEindeVindbaarheid() {
        return this.datumEindeVindbaarheid;
    }
    
    public void setDatumEindeVindbaarheid(Date datumEindeVindbaarheid) {
        this.datumEindeVindbaarheid = datumEindeVindbaarheid;
    }


    
    @Column(name="IndInstroomAchterstand")
    public Boolean getIndInstroomAchterstand() {
        return this.indInstroomAchterstand;
    }
    
    public void setIndInstroomAchterstand(Boolean indInstroomAchterstand) {
        this.indInstroomAchterstand = indInstroomAchterstand;
    }


@XmlTransient
@JsonIgnore
@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="Cir_Insolventie_Cir_Handelsnaam", catalog="cir", joinColumns = { 
        @JoinColumn(name="Insolventie_ID", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Handelsnaam_ID", nullable=false, updatable=false) })
    public Set<CirHandelsnaam> getCirHandelsnaams() {
        return this.cirHandelsnaams;
    }
    
    public void setCirHandelsnaams(Set<CirHandelsnaam> cirHandelsnaams) {
        this.cirHandelsnaams = cirHandelsnaams;
    }


@XmlTransient
@JsonIgnore
@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="Cir_Insolventie_Cir_Cbv", catalog="cir", joinColumns = { 
        @JoinColumn(name="Insolventie_ID", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="CBV_ID", nullable=false, updatable=false) })
    public Set<CirCbv> getCirCbvs() {
        return this.cirCbvs;
    }
    
    public void setCirCbvs(Set<CirCbv> cirCbvs) {
        this.cirCbvs = cirCbvs;
    }


@XmlTransient
@JsonIgnore
@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="Cir_Insolventie_Cir_Adres", catalog="cir", joinColumns = { 
        @JoinColumn(name="Insolventie_ID", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Adres_ID", nullable=false, updatable=false) })
    public Set<CirAdres> getCirAdreses() {
        return this.cirAdreses;
    }
    
    public void setCirAdreses(Set<CirAdres> cirAdreses) {
        this.cirAdreses = cirAdreses;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="cirInsolventie")
    public Set<CirPublicatie> getCirPublicaties() {
        return this.cirPublicaties;
    }
    
    public void setCirPublicaties(Set<CirPublicatie> cirPublicaties) {
        this.cirPublicaties = cirPublicaties;
    }





}


