package nl.devoorkant.sbdr.cir.data.model;
// Generated Apr 14, 2016 7:26:47 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * CirPersoon generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="CirCirPersoon")
@Table(name="Cir_Persoon"
)
public class CirPersoon  implements java.io.Serializable {


     private Integer id;
     private String rechtsPersoonlijkheid;
     private String voornaam;
     private String voorletters;
     private String voorvoegsel;
     private String naam;
     private Date datumGeboren;
     private String plaatsGeboren;
     private String landGeboren;
     private Date datumOverlijden;
     private String nummerKvK;
     private String plaatsKvK;
     private Set<CirInsolventie> cirInsolventies = new HashSet<CirInsolventie>(0);
     private Set<Resultaat> resultaats = new HashSet<Resultaat>(0);

    public CirPersoon() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }


    
    @Column(name="RechtsPersoonlijkheid", nullable=false, length=40)
    public String getRechtsPersoonlijkheid() {
        return this.rechtsPersoonlijkheid;
    }
    
    public void setRechtsPersoonlijkheid(String rechtsPersoonlijkheid) {
        this.rechtsPersoonlijkheid = rechtsPersoonlijkheid;
    }


    
    @Column(name="Voornaam", length=100)
    public String getVoornaam() {
        return this.voornaam;
    }
    
    public void setVoornaam(String voornaam) {
        this.voornaam = voornaam;
    }


    
    @Column(name="Voorletters", length=20)
    public String getVoorletters() {
        return this.voorletters;
    }
    
    public void setVoorletters(String voorletters) {
        this.voorletters = voorletters;
    }


    
    @Column(name="Voorvoegsel", length=20)
    public String getVoorvoegsel() {
        return this.voorvoegsel;
    }
    
    public void setVoorvoegsel(String voorvoegsel) {
        this.voorvoegsel = voorvoegsel;
    }


    
    @Column(name="Naam", length=200)
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.DATE)
    @Column(name="DatumGeboren", length=10)
    public Date getDatumGeboren() {
        return this.datumGeboren;
    }
    
    public void setDatumGeboren(Date datumGeboren) {
        this.datumGeboren = datumGeboren;
    }


    
    @Column(name="PlaatsGeboren", length=40)
    public String getPlaatsGeboren() {
        return this.plaatsGeboren;
    }
    
    public void setPlaatsGeboren(String plaatsGeboren) {
        this.plaatsGeboren = plaatsGeboren;
    }


    
    @Column(name="LandGeboren", length=50)
    public String getLandGeboren() {
        return this.landGeboren;
    }
    
    public void setLandGeboren(String landGeboren) {
        this.landGeboren = landGeboren;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.DATE)
    @Column(name="DatumOverlijden", length=10)
    public Date getDatumOverlijden() {
        return this.datumOverlijden;
    }
    
    public void setDatumOverlijden(Date datumOverlijden) {
        this.datumOverlijden = datumOverlijden;
    }


    
    @Column(name="NummerKvK", length=8)
    public String getNummerKvK() {
        return this.nummerKvK;
    }
    
    public void setNummerKvK(String nummerKvK) {
        this.nummerKvK = nummerKvK;
    }


    
    @Column(name="PlaatsKvK", length=40)
    public String getPlaatsKvK() {
        return this.plaatsKvK;
    }
    
    public void setPlaatsKvK(String plaatsKvK) {
        this.plaatsKvK = plaatsKvK;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="cirPersoon")
    public Set<CirInsolventie> getCirInsolventies() {
        return this.cirInsolventies;
    }
    
    public void setCirInsolventies(Set<CirInsolventie> cirInsolventies) {
        this.cirInsolventies = cirInsolventies;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="cirPersoon")
    public Set<Resultaat> getResultaats() {
        return this.resultaats;
    }
    
    public void setResultaats(Set<Resultaat> resultaats) {
        this.resultaats = resultaats;
    }





}


