package nl.devoorkant.sbdr.cir.data.model;
// Generated Apr 14, 2016 7:26:47 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * CirPublicatiekenmerk generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="CirCirPublicatiekenmerk")
@Table(name="Cir_Publicatiekenmerk"
    , uniqueConstraints = @UniqueConstraint(columnNames="PublicatieKenmerk") 
)
public class CirPublicatiekenmerk  implements java.io.Serializable {


     private Integer id;
     private String publicatieKenmerk;
     private Date tijdExtractie;
     private Date tijdVerwerkt;

    public CirPublicatiekenmerk() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }


    
    @Column(name="PublicatieKenmerk", unique=true, nullable=false, length=40)
    public String getPublicatieKenmerk() {
        return this.publicatieKenmerk;
    }
    
    public void setPublicatieKenmerk(String publicatieKenmerk) {
        this.publicatieKenmerk = publicatieKenmerk;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TijdExtractie", nullable=false, length=19)
    public Date getTijdExtractie() {
        return this.tijdExtractie;
    }
    
    public void setTijdExtractie(Date tijdExtractie) {
        this.tijdExtractie = tijdExtractie;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TijdVerwerkt", length=19)
    public Date getTijdVerwerkt() {
        return this.tijdVerwerkt;
    }
    
    public void setTijdVerwerkt(Date tijdVerwerkt) {
        this.tijdVerwerkt = tijdVerwerkt;
    }





}


