package nl.devoorkant.sbdr.cir.data.model;
// Generated Apr 14, 2016 7:26:47 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * CirPublicatie generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="CirCirPublicatie")
@Table(name="Cir_Publicatie"
)
public class CirPublicatie  implements java.io.Serializable {


     private Integer id;
     private CirPublicatiesoort cirPublicatiesoort;
     private CirZittingslocatie cirZittingslocatie;
     private CirInsolventie cirInsolventie;
     private String publicatieKenmerk;
     private Date datumPublicatie;
     private String publicatieOmschrijving;
     private String codePublicerendeInstantie;

    public CirPublicatie() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CodePublicatieSoort", nullable=false)
    public CirPublicatiesoort getCirPublicatiesoort() {
        return this.cirPublicatiesoort;
    }
    
    public void setCirPublicatiesoort(CirPublicatiesoort cirPublicatiesoort) {
        this.cirPublicatiesoort = cirPublicatiesoort;
    }



    @Transient
    public String getCirPublicatiesoortCode() {
        return this.cirPublicatiesoort == null ? null : this.cirPublicatiesoort.getCode();
    }

    public void setCirPublicatiesoortCode(String code) {
        if (code == null) {
            this.cirPublicatiesoort = null;
        } else {
            CirPublicatiesoort obj = new CirPublicatiesoort();
            obj.setCode(code);
            this.cirPublicatiesoort = obj;
        }
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ZittingsLocatie_ID")
    public CirZittingslocatie getCirZittingslocatie() {
        return this.cirZittingslocatie;
    }
    
    public void setCirZittingslocatie(CirZittingslocatie cirZittingslocatie) {
        this.cirZittingslocatie = cirZittingslocatie;
    }



    @Transient
    public Integer getCirZittingslocatieId() {
        return this.cirZittingslocatie == null ? null : this.cirZittingslocatie.getId();
    }

    public void setCirZittingslocatieId(Integer id) {
        if (id == null) {
            this.cirZittingslocatie = null;
        } else {
            CirZittingslocatie obj = new CirZittingslocatie();
            obj.setId(id);
            this.cirZittingslocatie = obj;
        }
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Insolventie_ID")
    public CirInsolventie getCirInsolventie() {
        return this.cirInsolventie;
    }
    
    public void setCirInsolventie(CirInsolventie cirInsolventie) {
        this.cirInsolventie = cirInsolventie;
    }



    @Transient
    public Integer getCirInsolventieId() {
        return this.cirInsolventie == null ? null : this.cirInsolventie.getId();
    }

    public void setCirInsolventieId(Integer id) {
        if (id == null) {
            this.cirInsolventie = null;
        } else {
            CirInsolventie obj = new CirInsolventie();
            obj.setId(id);
            this.cirInsolventie = obj;
        }
    }


    
    @Column(name="PublicatieKenmerk", length=40)
    public String getPublicatieKenmerk() {
        return this.publicatieKenmerk;
    }
    
    public void setPublicatieKenmerk(String publicatieKenmerk) {
        this.publicatieKenmerk = publicatieKenmerk;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.DATE)
    @Column(name="DatumPublicatie", nullable=false, length=10)
    public Date getDatumPublicatie() {
        return this.datumPublicatie;
    }
    
    public void setDatumPublicatie(Date datumPublicatie) {
        this.datumPublicatie = datumPublicatie;
    }


    
    @Column(name="PublicatieOmschrijving", nullable=false, length=1024)
    public String getPublicatieOmschrijving() {
        return this.publicatieOmschrijving;
    }
    
    public void setPublicatieOmschrijving(String publicatieOmschrijving) {
        this.publicatieOmschrijving = publicatieOmschrijving;
    }


    
    @Column(name="CodePublicerendeInstantie", nullable=false, length=40)
    public String getCodePublicerendeInstantie() {
        return this.codePublicerendeInstantie;
    }
    
    public void setCodePublicerendeInstantie(String codePublicerendeInstantie) {
        this.codePublicerendeInstantie = codePublicerendeInstantie;
    }





}


