package nl.devoorkant.sbdr.cir.data.model;
// Generated Apr 14, 2016 7:26:47 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * Configuratie generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="CirConfiguratie")
@Table(name="Configuratie"
)
public class Configuratie  implements java.io.Serializable {


     private String code;
     private String omschrijving;
     private String waarde;
     private Boolean indTonen;

    public Configuratie() {
    }

   
     @Id 

    
    @Column(name="Code", unique=true, nullable=false, length=5)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }


    
    @Column(name="Omschrijving", nullable=false)
    public String getOmschrijving() {
        return this.omschrijving;
    }
    
    public void setOmschrijving(String omschrijving) {
        this.omschrijving = omschrijving;
    }


    
    @Column(name="Waarde")
    public String getWaarde() {
        return this.waarde;
    }
    
    public void setWaarde(String waarde) {
        this.waarde = waarde;
    }


    
    @Column(name="IndTonen")
    public Boolean getIndTonen() {
        return this.indTonen;
    }
    
    public void setIndTonen(Boolean indTonen) {
        this.indTonen = indTonen;
    }





}


