package nl.devoorkant.sbdr.cir.data.model;
// Generated Apr 14, 2016 7:26:47 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * Input generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="CirInput")
@Table(name="Input"
)
public class Input  implements java.io.Serializable {


     private Integer inputId;
     private Batch batch;
     private String codeResultaatType;
     private String ingevoerdDoor;
     private Date tijdIngevoerd;
     private Date tijdVerwerkt;
     private String referentieNummer;
     private String naam;
     private String voorvoegsel;
     private String initialen;
     private Date datumGeboren;
     private String postcode;
     private String plaats;
     private String huisNummer;
     private String kvKnummer;
     private Set<Resultaat> resultaats = new HashSet<Resultaat>(0);

    public Input() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Input_ID", unique=true, nullable=false)
    public Integer getInputId() {
        return this.inputId;
    }
    
    public void setInputId(Integer inputId) {
        this.inputId = inputId;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Batch_ID")
    public Batch getBatch() {
        return this.batch;
    }
    
    public void setBatch(Batch batch) {
        this.batch = batch;
    }



    @Transient
    public Integer getBatchBatchId() {
        return this.batch == null ? null : this.batch.getBatchId();
    }

    public void setBatchBatchId(Integer batchId) {
        if (batchId == null) {
            this.batch = null;
        } else {
            Batch obj = new Batch();
            obj.setBatchId(batchId);
            this.batch = obj;
        }
    }


    
    @Column(name="CodeResultaatType", length=5)
    public String getCodeResultaatType() {
        return this.codeResultaatType;
    }
    
    public void setCodeResultaatType(String codeResultaatType) {
        this.codeResultaatType = codeResultaatType;
    }


    
    @Column(name="IngevoerdDoor", nullable=false, length=40)
    public String getIngevoerdDoor() {
        return this.ingevoerdDoor;
    }
    
    public void setIngevoerdDoor(String ingevoerdDoor) {
        this.ingevoerdDoor = ingevoerdDoor;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TijdIngevoerd", nullable=false, length=19)
    public Date getTijdIngevoerd() {
        return this.tijdIngevoerd;
    }
    
    public void setTijdIngevoerd(Date tijdIngevoerd) {
        this.tijdIngevoerd = tijdIngevoerd;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TijdVerwerkt", length=19)
    public Date getTijdVerwerkt() {
        return this.tijdVerwerkt;
    }
    
    public void setTijdVerwerkt(Date tijdVerwerkt) {
        this.tijdVerwerkt = tijdVerwerkt;
    }


    
    @Column(name="ReferentieNummer", length=40)
    public String getReferentieNummer() {
        return this.referentieNummer;
    }
    
    public void setReferentieNummer(String referentieNummer) {
        this.referentieNummer = referentieNummer;
    }


    
    @Column(name="Naam", length=40)
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }


    
    @Column(name="Voorvoegsel", length=40)
    public String getVoorvoegsel() {
        return this.voorvoegsel;
    }
    
    public void setVoorvoegsel(String voorvoegsel) {
        this.voorvoegsel = voorvoegsel;
    }


    
    @Column(name="Initialen", length=40)
    public String getInitialen() {
        return this.initialen;
    }
    
    public void setInitialen(String initialen) {
        this.initialen = initialen;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.DATE)
    @Column(name="DatumGeboren", length=10)
    public Date getDatumGeboren() {
        return this.datumGeboren;
    }
    
    public void setDatumGeboren(Date datumGeboren) {
        this.datumGeboren = datumGeboren;
    }


    
    @Column(name="Postcode", length=7)
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }


    
    @Column(name="Plaats", length=60)
    public String getPlaats() {
        return this.plaats;
    }
    
    public void setPlaats(String plaats) {
        this.plaats = plaats;
    }


    
    @Column(name="HuisNummer", length=10)
    public String getHuisNummer() {
        return this.huisNummer;
    }
    
    public void setHuisNummer(String huisNummer) {
        this.huisNummer = huisNummer;
    }


    
    @Column(name="KvKNummer", length=40)
    public String getKvKnummer() {
        return this.kvKnummer;
    }
    
    public void setKvKnummer(String kvKnummer) {
        this.kvKnummer = kvKnummer;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="input")
    public Set<Resultaat> getResultaats() {
        return this.resultaats;
    }
    
    public void setResultaats(Set<Resultaat> resultaats) {
        this.resultaats = resultaats;
    }





}


