package nl.devoorkant.sbdr.cir.data.model;
// Generated Apr 14, 2016 7:26:47 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * Resultaat generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="CirResultaat")
@Table(name="Resultaat"
)
public class Resultaat  implements java.io.Serializable {


     private Integer resultaatId;
     private Input input;
     private CirPersoon cirPersoon;
     private ResultaatType resultaatType;
     private Date tijdScore;
     private long score;
     private String card;

    public Resultaat() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Resultaat_ID", unique=true, nullable=false)
    public Integer getResultaatId() {
        return this.resultaatId;
    }
    
    public void setResultaatId(Integer resultaatId) {
        this.resultaatId = resultaatId;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Input_ID", nullable=false)
    public Input getInput() {
        return this.input;
    }
    
    public void setInput(Input input) {
        this.input = input;
    }



    @Transient
    public Integer getInputInputId() {
        return this.input == null ? null : this.input.getInputId();
    }

    public void setInputInputId(Integer inputId) {
        if (inputId == null) {
            this.input = null;
        } else {
            Input obj = new Input();
            obj.setInputId(inputId);
            this.input = obj;
        }
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CIR_Persoon_ID", nullable=false)
    public CirPersoon getCirPersoon() {
        return this.cirPersoon;
    }
    
    public void setCirPersoon(CirPersoon cirPersoon) {
        this.cirPersoon = cirPersoon;
    }



    @Transient
    public Integer getCirPersoonId() {
        return this.cirPersoon == null ? null : this.cirPersoon.getId();
    }

    public void setCirPersoonId(Integer id) {
        if (id == null) {
            this.cirPersoon = null;
        } else {
            CirPersoon obj = new CirPersoon();
            obj.setId(id);
            this.cirPersoon = obj;
        }
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CodeResultaatType")
    public ResultaatType getResultaatType() {
        return this.resultaatType;
    }
    
    public void setResultaatType(ResultaatType resultaatType) {
        this.resultaatType = resultaatType;
    }



    @Transient
    public String getResultaatTypeCode() {
        return this.resultaatType == null ? null : this.resultaatType.getCode();
    }

    public void setResultaatTypeCode(String code) {
        if (code == null) {
            this.resultaatType = null;
        } else {
            ResultaatType obj = new ResultaatType();
            obj.setCode(code);
            this.resultaatType = obj;
        }
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TijdScore", nullable=false, length=19)
    public Date getTijdScore() {
        return this.tijdScore;
    }
    
    public void setTijdScore(Date tijdScore) {
        this.tijdScore = tijdScore;
    }


    
    @Column(name="Score", nullable=false, precision=10, scale=0)
    public long getScore() {
        return this.score;
    }
    
    public void setScore(long score) {
        this.score = score;
    }


    
    @Column(name="Card", nullable=false, length=50)
    public String getCard() {
        return this.card;
    }
    
    public void setCard(String card) {
        this.card = card;
    }





}


