package nl.devoorkant.sbdr.cir.data.model;
// Generated Apr 14, 2016 7:26:47 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * Statistieken generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="CirStatistieken")
@Table(name="Statistieken"
)
public class Statistieken  implements java.io.Serializable {


     private Integer statistiekenId;
     private Date datum;
     private Integer nrInsolventiesTotaal;
     private Integer nrInsolventiesVerwijderd;
     private Integer nrInsolventiesToegevoegd;

    public Statistieken() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Statistieken_ID", unique=true, nullable=false)
    public Integer getStatistiekenId() {
        return this.statistiekenId;
    }
    
    public void setStatistiekenId(Integer statistiekenId) {
        this.statistiekenId = statistiekenId;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.DATE)
    @Column(name="Datum", length=10)
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }


    
    @Column(name="NrInsolventiesTotaal")
    public Integer getNrInsolventiesTotaal() {
        return this.nrInsolventiesTotaal;
    }
    
    public void setNrInsolventiesTotaal(Integer nrInsolventiesTotaal) {
        this.nrInsolventiesTotaal = nrInsolventiesTotaal;
    }


    
    @Column(name="NrInsolventiesVerwijderd")
    public Integer getNrInsolventiesVerwijderd() {
        return this.nrInsolventiesVerwijderd;
    }
    
    public void setNrInsolventiesVerwijderd(Integer nrInsolventiesVerwijderd) {
        this.nrInsolventiesVerwijderd = nrInsolventiesVerwijderd;
    }


    
    @Column(name="NrInsolventiesToegevoegd")
    public Integer getNrInsolventiesToegevoegd() {
        return this.nrInsolventiesToegevoegd;
    }
    
    public void setNrInsolventiesToegevoegd(Integer nrInsolventiesToegevoegd) {
        this.nrInsolventiesToegevoegd = nrInsolventiesToegevoegd;
    }





}


