package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * AlertView generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="AlertView")
@Table(name="AlertView"
)
public class AlertView  implements java.io.Serializable {


     private String alertViewId;
     private Bedrijf bedrijf;
     private Integer alertId;
     private Integer gebruikerId;
     private String type;
     private String kvkNummer;
     private String bedrijfsNaam;
     private Integer monitoringId;
     private Integer meldingId;
     private Integer supportId;
     private String referentieNummer;
     private String supportType;
     private String meldingStatus;
     private Date datum;
     private String aanvangFaillissement;
     private String indicatieFaillissement;
     private String aanvangSurseance;
     private String indicatieSurseance;
     private Long indEigenBedrijf;
     private Long indMonitoringBedrijf;
     private Integer monitoringDoorBedrijfId;
     private Integer meldingDoorBedrijfId;
     private Integer meldingDoorGebruikerId;
     private Integer bestemdVoorBedrijfId;

    public AlertView() {
    }

   
     @Id 

    
    @Column(name="alertView_Id", length=36)
    public String getAlertViewId() {
        return this.alertViewId;
    }
    
    public void setAlertViewId(String alertViewId) {
        this.alertViewId = alertViewId;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bedrijf_Id")
    public Bedrijf getBedrijf() {
        return this.bedrijf;
    }
    
    public void setBedrijf(Bedrijf bedrijf) {
        this.bedrijf = bedrijf;
    }



    @Transient
    public Integer getBedrijfBedrijfId() {
        return this.bedrijf == null ? null : this.bedrijf.getBedrijfId();
    }

    public void setBedrijfBedrijfId(Integer bedrijfId) {
        if (bedrijfId == null) {
            this.bedrijf = null;
        } else {
            Bedrijf obj = new Bedrijf();
            obj.setBedrijfId(bedrijfId);
            this.bedrijf = obj;
        }
    }


    
    @Column(name="alert_Id")
    public Integer getAlertId() {
        return this.alertId;
    }
    
    public void setAlertId(Integer alertId) {
        this.alertId = alertId;
    }


    
    @Column(name="gebruiker_Id")
    public Integer getGebruikerId() {
        return this.gebruikerId;
    }
    
    public void setGebruikerId(Integer gebruikerId) {
        this.gebruikerId = gebruikerId;
    }


    
    @Column(name="type", nullable=false, length=3)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }


    
    @Column(name="kvkNummer", length=20)
    public String getKvkNummer() {
        return this.kvkNummer;
    }
    
    public void setKvkNummer(String kvkNummer) {
        this.kvkNummer = kvkNummer;
    }


    
    @Column(name="bedrijfsNaam")
    public String getBedrijfsNaam() {
        return this.bedrijfsNaam;
    }
    
    public void setBedrijfsNaam(String bedrijfsNaam) {
        this.bedrijfsNaam = bedrijfsNaam;
    }


    
    @Column(name="monitoring_Id")
    public Integer getMonitoringId() {
        return this.monitoringId;
    }
    
    public void setMonitoringId(Integer monitoringId) {
        this.monitoringId = monitoringId;
    }


    
    @Column(name="melding_Id")
    public Integer getMeldingId() {
        return this.meldingId;
    }
    
    public void setMeldingId(Integer meldingId) {
        this.meldingId = meldingId;
    }


    
    @Column(name="support_Id")
    public Integer getSupportId() {
        return this.supportId;
    }
    
    public void setSupportId(Integer supportId) {
        this.supportId = supportId;
    }


    
    @Column(name="referentieNummer", length=50)
    public String getReferentieNummer() {
        return this.referentieNummer;
    }
    
    public void setReferentieNummer(String referentieNummer) {
        this.referentieNummer = referentieNummer;
    }


    
    @Column(name="supportType", length=50)
    public String getSupportType() {
        return this.supportType;
    }
    
    public void setSupportType(String supportType) {
        this.supportType = supportType;
    }


    
    @Column(name="meldingStatus", length=3)
    public String getMeldingStatus() {
        return this.meldingStatus;
    }
    
    public void setMeldingStatus(String meldingStatus) {
        this.meldingStatus = meldingStatus;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datum", length=19)
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }


    
    @Column(name="aanvangFaillissement", length=100)
    public String getAanvangFaillissement() {
        return this.aanvangFaillissement;
    }
    
    public void setAanvangFaillissement(String aanvangFaillissement) {
        this.aanvangFaillissement = aanvangFaillissement;
    }


    
    @Column(name="indicatieFaillissement", length=50)
    public String getIndicatieFaillissement() {
        return this.indicatieFaillissement;
    }
    
    public void setIndicatieFaillissement(String indicatieFaillissement) {
        this.indicatieFaillissement = indicatieFaillissement;
    }


    
    @Column(name="aanvangSurseance", length=100)
    public String getAanvangSurseance() {
        return this.aanvangSurseance;
    }
    
    public void setAanvangSurseance(String aanvangSurseance) {
        this.aanvangSurseance = aanvangSurseance;
    }


    
    @Column(name="indicatieSurseance", length=50)
    public String getIndicatieSurseance() {
        return this.indicatieSurseance;
    }
    
    public void setIndicatieSurseance(String indicatieSurseance) {
        this.indicatieSurseance = indicatieSurseance;
    }


    
    @Column(name="indEigenBedrijf")
    public Long getIndEigenBedrijf() {
        return this.indEigenBedrijf;
    }
    
    public void setIndEigenBedrijf(Long indEigenBedrijf) {
        this.indEigenBedrijf = indEigenBedrijf;
    }


    
    @Column(name="indMonitoringBedrijf")
    public Long getIndMonitoringBedrijf() {
        return this.indMonitoringBedrijf;
    }
    
    public void setIndMonitoringBedrijf(Long indMonitoringBedrijf) {
        this.indMonitoringBedrijf = indMonitoringBedrijf;
    }


    
    @Column(name="monitoringDoorBedrijf_Id")
    public Integer getMonitoringDoorBedrijfId() {
        return this.monitoringDoorBedrijfId;
    }
    
    public void setMonitoringDoorBedrijfId(Integer monitoringDoorBedrijfId) {
        this.monitoringDoorBedrijfId = monitoringDoorBedrijfId;
    }


    
    @Column(name="meldingDoorBedrijf_Id")
    public Integer getMeldingDoorBedrijfId() {
        return this.meldingDoorBedrijfId;
    }
    
    public void setMeldingDoorBedrijfId(Integer meldingDoorBedrijfId) {
        this.meldingDoorBedrijfId = meldingDoorBedrijfId;
    }


    
    @Column(name="meldingDoorGebruiker_Id")
    public Integer getMeldingDoorGebruikerId() {
        return this.meldingDoorGebruikerId;
    }
    
    public void setMeldingDoorGebruikerId(Integer meldingDoorGebruikerId) {
        this.meldingDoorGebruikerId = meldingDoorGebruikerId;
    }


    
    @Column(name="BestemdVoorBedrijf_Id")
    public Integer getBestemdVoorBedrijfId() {
        return this.bestemdVoorBedrijfId;
    }
    
    public void setBestemdVoorBedrijfId(Integer bestemdVoorBedrijfId) {
        this.bestemdVoorBedrijfId = bestemdVoorBedrijfId;
    }





}


