package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * BedrijfRol generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="BedrijfRol")
@Table(name="BedrijfRol"
)
public class BedrijfRol  implements java.io.Serializable {


     private Integer bedrijfRolId;
     private String code;
     private String omschrijving;
     private Set<Bedrijf> bedrijven = new HashSet<Bedrijf>(0);

    public BedrijfRol() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="BedrijfRol_ID", unique=true, nullable=false)
    public Integer getBedrijfRolId() {
        return this.bedrijfRolId;
    }
    
    public void setBedrijfRolId(Integer bedrijfRolId) {
        this.bedrijfRolId = bedrijfRolId;
    }


    
    @Column(name="Code", nullable=false, length=3)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }


    
    @Column(name="Omschrijving", nullable=false, length=100)
    public String getOmschrijving() {
        return this.omschrijving;
    }
    
    public void setOmschrijving(String omschrijving) {
        this.omschrijving = omschrijving;
    }


@XmlTransient
@JsonIgnore
@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="BedrijfRol_Bedrijf", catalog="sbdr", joinColumns = { 
        @JoinColumn(name="BedrijfRol_ID", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Bedrijf_ID", nullable=false, updatable=false) })
    public Set<Bedrijf> getBedrijven() {
        return this.bedrijven;
    }
    
    public void setBedrijven(Set<Bedrijf> bedrijven) {
        this.bedrijven = bedrijven;
    }





}


