package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * Bedrijf generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="Bedrijf")
@Table(name="Bedrijf"
)
public class Bedrijf  implements java.io.Serializable {


     private Integer bedrijfId;
     private BedrijfStatus bedrijfStatus;
     private CIKvKDossier CIKvKDossier;
     private String kvKnummer;
     private String bedrijfsNaam;
     private String rechtsvorm;
     private String straat;
     private Integer huisNr;
     private String huisNrToevoeging;
     private String postcode;
     private String plaats;
     private Date datumWijziging;
     private boolean actief;
     private String sbdrNummer;
     private Integer rapportCounter;
     private String subDossier;
     private boolean adresOk;
     private boolean handmatigGewijzigd;
     private String postPostbus;
     private String postPostcode;
     private String postPlaats;
     private String hoofdNeven;
     private String accountGuid;
     private Date datumVerwerktExactOnline;
     private boolean bedrijfActief;
     private String telefoonnummer;
     private Set<GebruikerGroep> gebruikerGroepen = new HashSet<GebruikerGroep>(0);
     private Set<Monitoring> monitoringsForMonitoringDoorBedrijfId = new HashSet<Monitoring>(0);
     private Set<Alert> alertsForBedrijfId = new HashSet<Alert>(0);
     private Set<BedrijfHistorie> bedrijfHistories = new HashSet<BedrijfHistorie>(0);
     private Set<Document> documentsForRapportBedrijfId = new HashSet<Document>(0);
     private Set<Factuur> facturen = new HashSet<Factuur>(0);
     private Set<Monitoring> monitoringsForMonitoringVanBedrijfId = new HashSet<Monitoring>(0);
     private Set<Gebruiker> gebruikers = new HashSet<Gebruiker>(0);
     private Set<CustomMelding> customMeldings = new HashSet<CustomMelding>(0);
     private Set<Alert> alertsForAlertOverBedrijfId = new HashSet<Alert>(0);
     private Set<Persoon> personen = new HashSet<Persoon>(0);
     private Set<InternalProcess> internalProcesses = new HashSet<InternalProcess>(0);
     private Set<Melding> meldingsForMeldingDoorBedrijfId = new HashSet<Melding>(0);
     private Set<Melding> meldingsForMeldingOverBedrijfId = new HashSet<Melding>(0);
     private Set<Support> supports = new HashSet<Support>(0);
     private Set<Document> documentsForBedrijfId = new HashSet<Document>(0);
     private Set<Logging> loggings = new HashSet<Logging>(0);
     private Set<BedrijfRol> bedrijfRollen = new HashSet<BedrijfRol>(0);
     private Set<BedrijfManaged> bedrijvenManagedVanBedrijfId = new HashSet<BedrijfManaged>(0);

    public Bedrijf() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Bedrijf_ID", unique=true, nullable=false)
    public Integer getBedrijfId() {
        return this.bedrijfId;
    }
    
    public void setBedrijfId(Integer bedrijfId) {
        this.bedrijfId = bedrijfId;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BedrijfStatus")
    public BedrijfStatus getBedrijfStatus() {
        return this.bedrijfStatus;
    }
    
    public void setBedrijfStatus(BedrijfStatus bedrijfStatus) {
        this.bedrijfStatus = bedrijfStatus;
    }



    @Transient
    public String getBedrijfStatusCode() {
        return this.bedrijfStatus == null ? null : this.bedrijfStatus.getCode();
    }

    public void setBedrijfStatusCode(String code) {
        if (code == null) {
            this.bedrijfStatus = null;
        } else {
            BedrijfStatus obj = new BedrijfStatus();
            obj.setCode(code);
            this.bedrijfStatus = obj;
        }
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CIKvKDossier_ID")
    public CIKvKDossier getCIKvKDossier() {
        return this.CIKvKDossier;
    }
    
    public void setCIKvKDossier(CIKvKDossier CIKvKDossier) {
        this.CIKvKDossier = CIKvKDossier;
    }



    @Transient
    public Integer getCIKvKDossierCikvKdossierId() {
        return this.CIKvKDossier == null ? null : this.CIKvKDossier.getCikvKdossierId();
    }

    public void setCIKvKDossierCikvKdossierId(Integer cikvKdossierId) {
        if (cikvKdossierId == null) {
            this.CIKvKDossier = null;
        } else {
            CIKvKDossier obj = new CIKvKDossier();
            obj.setCikvKdossierId(cikvKdossierId);
            this.CIKvKDossier = obj;
        }
    }


    
    @Column(name="KvKNummer", nullable=false, length=20)
    public String getKvKnummer() {
        return this.kvKnummer;
    }
    
    public void setKvKnummer(String kvKnummer) {
        this.kvKnummer = kvKnummer;
    }


    
    @Column(name="BedrijfsNaam")
    public String getBedrijfsNaam() {
        return this.bedrijfsNaam;
    }
    
    public void setBedrijfsNaam(String bedrijfsNaam) {
        this.bedrijfsNaam = bedrijfsNaam;
    }


    
    @Column(name="Rechtsvorm", length=100)
    public String getRechtsvorm() {
        return this.rechtsvorm;
    }
    
    public void setRechtsvorm(String rechtsvorm) {
        this.rechtsvorm = rechtsvorm;
    }


    
    @Column(name="Straat", length=100)
    public String getStraat() {
        return this.straat;
    }
    
    public void setStraat(String straat) {
        this.straat = straat;
    }


    
    @Column(name="HuisNr")
    public Integer getHuisNr() {
        return this.huisNr;
    }
    
    public void setHuisNr(Integer huisNr) {
        this.huisNr = huisNr;
    }


    
    @Column(name="HuisNrToevoeging", length=35)
    public String getHuisNrToevoeging() {
        return this.huisNrToevoeging;
    }
    
    public void setHuisNrToevoeging(String huisNrToevoeging) {
        this.huisNrToevoeging = huisNrToevoeging;
    }


    
    @Column(name="Postcode", length=7)
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }


    
    @Column(name="Plaats", length=100)
    public String getPlaats() {
        return this.plaats;
    }
    
    public void setPlaats(String plaats) {
        this.plaats = plaats;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DatumWijziging", length=19)
    public Date getDatumWijziging() {
        return this.datumWijziging;
    }
    
    public void setDatumWijziging(Date datumWijziging) {
        this.datumWijziging = datumWijziging;
    }


    
    @Column(name="Actief", nullable=false)
    public boolean isActief() {
        return this.actief;
    }
    
    public void setActief(boolean actief) {
        this.actief = actief;
    }


    
    @Column(name="SbdrNummer", length=20)
    public String getSbdrNummer() {
        return this.sbdrNummer;
    }
    
    public void setSbdrNummer(String sbdrNummer) {
        this.sbdrNummer = sbdrNummer;
    }


    
    @Column(name="RapportCounter")
    public Integer getRapportCounter() {
        return this.rapportCounter;
    }
    
    public void setRapportCounter(Integer rapportCounter) {
        this.rapportCounter = rapportCounter;
    }


    
    @Column(name="SubDossier", length=20)
    public String getSubDossier() {
        return this.subDossier;
    }
    
    public void setSubDossier(String subDossier) {
        this.subDossier = subDossier;
    }


    
    @Column(name="AdresOk", nullable=false)
    public boolean isAdresOk() {
        return this.adresOk;
    }
    
    public void setAdresOk(boolean adresOk) {
        this.adresOk = adresOk;
    }


    
    @Column(name="HandmatigGewijzigd", nullable=false)
    public boolean isHandmatigGewijzigd() {
        return this.handmatigGewijzigd;
    }
    
    public void setHandmatigGewijzigd(boolean handmatigGewijzigd) {
        this.handmatigGewijzigd = handmatigGewijzigd;
    }


    
    @Column(name="PostPostbus", length=15)
    public String getPostPostbus() {
        return this.postPostbus;
    }
    
    public void setPostPostbus(String postPostbus) {
        this.postPostbus = postPostbus;
    }


    
    @Column(name="PostPostcode", length=10)
    public String getPostPostcode() {
        return this.postPostcode;
    }
    
    public void setPostPostcode(String postPostcode) {
        this.postPostcode = postPostcode;
    }


    
    @Column(name="PostPlaats", length=100)
    public String getPostPlaats() {
        return this.postPlaats;
    }
    
    public void setPostPlaats(String postPlaats) {
        this.postPlaats = postPlaats;
    }


    
    @Column(name="HoofdNeven", length=1)
    public String getHoofdNeven() {
        return this.hoofdNeven;
    }
    
    public void setHoofdNeven(String hoofdNeven) {
        this.hoofdNeven = hoofdNeven;
    }


    
    @Column(name="AccountGuid", length=36)
    public String getAccountGuid() {
        return this.accountGuid;
    }
    
    public void setAccountGuid(String accountGuid) {
        this.accountGuid = accountGuid;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DatumVerwerktExactOnline", length=19)
    public Date getDatumVerwerktExactOnline() {
        return this.datumVerwerktExactOnline;
    }
    
    public void setDatumVerwerktExactOnline(Date datumVerwerktExactOnline) {
        this.datumVerwerktExactOnline = datumVerwerktExactOnline;
    }


    
    @Column(name="BedrijfActief", nullable=false)
    public boolean isBedrijfActief() {
        return this.bedrijfActief;
    }
    
    public void setBedrijfActief(boolean bedrijfActief) {
        this.bedrijfActief = bedrijfActief;
    }


    
    @Column(name="Telefoonnummer", length=15)
    public String getTelefoonnummer() {
        return this.telefoonnummer;
    }
    
    public void setTelefoonnummer(String telefoonnummer) {
        this.telefoonnummer = telefoonnummer;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="bedrijf")
    public Set<GebruikerGroep> getGebruikerGroepen() {
        return this.gebruikerGroepen;
    }
    
    public void setGebruikerGroepen(Set<GebruikerGroep> gebruikerGroepen) {
        this.gebruikerGroepen = gebruikerGroepen;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="bedrijfByMonitoringDoorBedrijfId")
    public Set<Monitoring> getMonitoringsForMonitoringDoorBedrijfId() {
        return this.monitoringsForMonitoringDoorBedrijfId;
    }
    
    public void setMonitoringsForMonitoringDoorBedrijfId(Set<Monitoring> monitoringsForMonitoringDoorBedrijfId) {
        this.monitoringsForMonitoringDoorBedrijfId = monitoringsForMonitoringDoorBedrijfId;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="bedrijfByBedrijfId")
    public Set<Alert> getAlertsForBedrijfId() {
        return this.alertsForBedrijfId;
    }
    
    public void setAlertsForBedrijfId(Set<Alert> alertsForBedrijfId) {
        this.alertsForBedrijfId = alertsForBedrijfId;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="bedrijf")
    public Set<BedrijfHistorie> getBedrijfHistories() {
        return this.bedrijfHistories;
    }
    
    public void setBedrijfHistories(Set<BedrijfHistorie> bedrijfHistories) {
        this.bedrijfHistories = bedrijfHistories;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="bedrijfByRapportBedrijfId")
    public Set<Document> getDocumentsForRapportBedrijfId() {
        return this.documentsForRapportBedrijfId;
    }
    
    public void setDocumentsForRapportBedrijfId(Set<Document> documentsForRapportBedrijfId) {
        this.documentsForRapportBedrijfId = documentsForRapportBedrijfId;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="bedrijf")
    public Set<Factuur> getFacturen() {
        return this.facturen;
    }
    
    public void setFacturen(Set<Factuur> facturen) {
        this.facturen = facturen;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="bedrijfByMonitoringVanBedrijfId")
    public Set<Monitoring> getMonitoringsForMonitoringVanBedrijfId() {
        return this.monitoringsForMonitoringVanBedrijfId;
    }
    
    public void setMonitoringsForMonitoringVanBedrijfId(Set<Monitoring> monitoringsForMonitoringVanBedrijfId) {
        this.monitoringsForMonitoringVanBedrijfId = monitoringsForMonitoringVanBedrijfId;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="bedrijf")
    public Set<Gebruiker> getGebruikers() {
        return this.gebruikers;
    }
    
    public void setGebruikers(Set<Gebruiker> gebruikers) {
        this.gebruikers = gebruikers;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="bedrijf")
    public Set<CustomMelding> getCustomMeldings() {
        return this.customMeldings;
    }
    
    public void setCustomMeldings(Set<CustomMelding> customMeldings) {
        this.customMeldings = customMeldings;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="bedrijfByAlertOverBedrijfId")
    public Set<Alert> getAlertsForAlertOverBedrijfId() {
        return this.alertsForAlertOverBedrijfId;
    }
    
    public void setAlertsForAlertOverBedrijfId(Set<Alert> alertsForAlertOverBedrijfId) {
        this.alertsForAlertOverBedrijfId = alertsForAlertOverBedrijfId;
    }


@XmlTransient
@JsonIgnore
@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="Bedrijf_Persoon", catalog="sbdr", joinColumns = { 
        @JoinColumn(name="Bedrijf_ID", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Persoon_ID", nullable=false, updatable=false) })
    public Set<Persoon> getPersonen() {
        return this.personen;
    }
    
    public void setPersonen(Set<Persoon> personen) {
        this.personen = personen;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="bedrijf")
    public Set<InternalProcess> getInternalProcesses() {
        return this.internalProcesses;
    }
    
    public void setInternalProcesses(Set<InternalProcess> internalProcesses) {
        this.internalProcesses = internalProcesses;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="bedrijfByMeldingDoorBedrijfId")
    public Set<Melding> getMeldingsForMeldingDoorBedrijfId() {
        return this.meldingsForMeldingDoorBedrijfId;
    }
    
    public void setMeldingsForMeldingDoorBedrijfId(Set<Melding> meldingsForMeldingDoorBedrijfId) {
        this.meldingsForMeldingDoorBedrijfId = meldingsForMeldingDoorBedrijfId;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="bedrijfByMeldingOverBedrijfId")
    public Set<Melding> getMeldingsForMeldingOverBedrijfId() {
        return this.meldingsForMeldingOverBedrijfId;
    }
    
    public void setMeldingsForMeldingOverBedrijfId(Set<Melding> meldingsForMeldingOverBedrijfId) {
        this.meldingsForMeldingOverBedrijfId = meldingsForMeldingOverBedrijfId;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="bedrijf")
    public Set<Support> getSupports() {
        return this.supports;
    }
    
    public void setSupports(Set<Support> supports) {
        this.supports = supports;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="bedrijfByBedrijfId")
    public Set<Document> getDocumentsForBedrijfId() {
        return this.documentsForBedrijfId;
    }
    
    public void setDocumentsForBedrijfId(Set<Document> documentsForBedrijfId) {
        this.documentsForBedrijfId = documentsForBedrijfId;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="bedrijf")
    public Set<Logging> getLoggings() {
        return this.loggings;
    }
    
    public void setLoggings(Set<Logging> loggings) {
        this.loggings = loggings;
    }


@XmlTransient
@JsonIgnore
@ManyToMany(fetch=FetchType.LAZY, mappedBy="bedrijven")
    public Set<BedrijfRol> getBedrijfRollen() {
        return this.bedrijfRollen;
    }
    
    public void setBedrijfRollen(Set<BedrijfRol> bedrijfRollen) {
        this.bedrijfRollen = bedrijfRollen;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="bedrijf")
    public Set<BedrijfManaged> getBedrijvenManagedVanBedrijfId() {
        return this.bedrijvenManagedVanBedrijfId;
    }
    
    public void setBedrijvenManagedVanBedrijfId(Set<BedrijfManaged> bedrijvenManagedVanBedrijfId) {
        this.bedrijvenManagedVanBedrijfId = bedrijvenManagedVanBedrijfId;
    }


}


