package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * BedrijfHistorie generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="BedrijfHistorie")
@Table(name="BedrijfHistorie"
)
public class BedrijfHistorie  implements java.io.Serializable {


     private Integer bedrijfHistorieId;
     private BedrijfStatus bedrijfStatus;
     private Bedrijf bedrijf;
     private Integer cikvKdossierId;
     private String kvKnummer;
     private String bedrijfsNaam;
     private String rechtsvorm;
     private String straat;
     private Integer huisNr;
     private String huisNrToevoeging;
     private String postcode;
     private String plaats;
     private Date datumWijziging;
     private boolean actief;
     private String sbdrNummer;
     private Integer rapportCounter;
     private String subDossier;
     private boolean adresOk;
     private boolean handmatigGewijzigd;
     private String postPostbus;
     private String postPostcode;
     private String postPlaats;
     private String hoofdNeven;
     private String accountGuid;
     private Date datumVerwerktExactOnline;
     private boolean bedrijfActief;
     private String telefoonnummer;

    public BedrijfHistorie() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="BedrijfHistorie_ID", unique=true, nullable=false)
    public Integer getBedrijfHistorieId() {
        return this.bedrijfHistorieId;
    }
    
    public void setBedrijfHistorieId(Integer bedrijfHistorieId) {
        this.bedrijfHistorieId = bedrijfHistorieId;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BedrijfStatus")
    public BedrijfStatus getBedrijfStatus() {
        return this.bedrijfStatus;
    }
    
    public void setBedrijfStatus(BedrijfStatus bedrijfStatus) {
        this.bedrijfStatus = bedrijfStatus;
    }



    @Transient
    public String getBedrijfStatusCode() {
        return this.bedrijfStatus == null ? null : this.bedrijfStatus.getCode();
    }

    public void setBedrijfStatusCode(String code) {
        if (code == null) {
            this.bedrijfStatus = null;
        } else {
            BedrijfStatus obj = new BedrijfStatus();
            obj.setCode(code);
            this.bedrijfStatus = obj;
        }
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Bedrijf_ID", nullable=false)
    public Bedrijf getBedrijf() {
        return this.bedrijf;
    }
    
    public void setBedrijf(Bedrijf bedrijf) {
        this.bedrijf = bedrijf;
    }



    @Transient
    public Integer getBedrijfBedrijfId() {
        return this.bedrijf == null ? null : this.bedrijf.getBedrijfId();
    }

    public void setBedrijfBedrijfId(Integer bedrijfId) {
        if (bedrijfId == null) {
            this.bedrijf = null;
        } else {
            Bedrijf obj = new Bedrijf();
            obj.setBedrijfId(bedrijfId);
            this.bedrijf = obj;
        }
    }


    
    @Column(name="CIKvKDossier_ID")
    public Integer getCikvKdossierId() {
        return this.cikvKdossierId;
    }
    
    public void setCikvKdossierId(Integer cikvKdossierId) {
        this.cikvKdossierId = cikvKdossierId;
    }


    
    @Column(name="KvKNummer", nullable=false, length=20)
    public String getKvKnummer() {
        return this.kvKnummer;
    }
    
    public void setKvKnummer(String kvKnummer) {
        this.kvKnummer = kvKnummer;
    }


    
    @Column(name="BedrijfsNaam")
    public String getBedrijfsNaam() {
        return this.bedrijfsNaam;
    }
    
    public void setBedrijfsNaam(String bedrijfsNaam) {
        this.bedrijfsNaam = bedrijfsNaam;
    }


    
    @Column(name="Rechtsvorm", length=100)
    public String getRechtsvorm() {
        return this.rechtsvorm;
    }
    
    public void setRechtsvorm(String rechtsvorm) {
        this.rechtsvorm = rechtsvorm;
    }


    
    @Column(name="Straat", length=100)
    public String getStraat() {
        return this.straat;
    }
    
    public void setStraat(String straat) {
        this.straat = straat;
    }


    
    @Column(name="HuisNr")
    public Integer getHuisNr() {
        return this.huisNr;
    }
    
    public void setHuisNr(Integer huisNr) {
        this.huisNr = huisNr;
    }


    
    @Column(name="HuisNrToevoeging", length=35)
    public String getHuisNrToevoeging() {
        return this.huisNrToevoeging;
    }
    
    public void setHuisNrToevoeging(String huisNrToevoeging) {
        this.huisNrToevoeging = huisNrToevoeging;
    }


    
    @Column(name="Postcode", length=7)
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }


    
    @Column(name="Plaats", length=100)
    public String getPlaats() {
        return this.plaats;
    }
    
    public void setPlaats(String plaats) {
        this.plaats = plaats;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DatumWijziging", length=19)
    public Date getDatumWijziging() {
        return this.datumWijziging;
    }
    
    public void setDatumWijziging(Date datumWijziging) {
        this.datumWijziging = datumWijziging;
    }


    
    @Column(name="Actief", nullable=false)
    public boolean isActief() {
        return this.actief;
    }
    
    public void setActief(boolean actief) {
        this.actief = actief;
    }


    
    @Column(name="SbdrNummer", length=20)
    public String getSbdrNummer() {
        return this.sbdrNummer;
    }
    
    public void setSbdrNummer(String sbdrNummer) {
        this.sbdrNummer = sbdrNummer;
    }


    
    @Column(name="RapportCounter")
    public Integer getRapportCounter() {
        return this.rapportCounter;
    }
    
    public void setRapportCounter(Integer rapportCounter) {
        this.rapportCounter = rapportCounter;
    }


    
    @Column(name="SubDossier", length=20)
    public String getSubDossier() {
        return this.subDossier;
    }
    
    public void setSubDossier(String subDossier) {
        this.subDossier = subDossier;
    }


    
    @Column(name="AdresOk", nullable=false)
    public boolean isAdresOk() {
        return this.adresOk;
    }
    
    public void setAdresOk(boolean adresOk) {
        this.adresOk = adresOk;
    }


    
    @Column(name="HandmatigGewijzigd", nullable=false)
    public boolean isHandmatigGewijzigd() {
        return this.handmatigGewijzigd;
    }
    
    public void setHandmatigGewijzigd(boolean handmatigGewijzigd) {
        this.handmatigGewijzigd = handmatigGewijzigd;
    }


    
    @Column(name="PostPostbus", length=15)
    public String getPostPostbus() {
        return this.postPostbus;
    }
    
    public void setPostPostbus(String postPostbus) {
        this.postPostbus = postPostbus;
    }


    
    @Column(name="PostPostcode", length=10)
    public String getPostPostcode() {
        return this.postPostcode;
    }
    
    public void setPostPostcode(String postPostcode) {
        this.postPostcode = postPostcode;
    }


    
    @Column(name="PostPlaats", length=100)
    public String getPostPlaats() {
        return this.postPlaats;
    }
    
    public void setPostPlaats(String postPlaats) {
        this.postPlaats = postPlaats;
    }


    
    @Column(name="HoofdNeven", length=1)
    public String getHoofdNeven() {
        return this.hoofdNeven;
    }
    
    public void setHoofdNeven(String hoofdNeven) {
        this.hoofdNeven = hoofdNeven;
    }


    
    @Column(name="AccountGuid", length=36)
    public String getAccountGuid() {
        return this.accountGuid;
    }
    
    public void setAccountGuid(String accountGuid) {
        this.accountGuid = accountGuid;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DatumVerwerktExactOnline", length=19)
    public Date getDatumVerwerktExactOnline() {
        return this.datumVerwerktExactOnline;
    }
    
    public void setDatumVerwerktExactOnline(Date datumVerwerktExactOnline) {
        this.datumVerwerktExactOnline = datumVerwerktExactOnline;
    }


    
    @Column(name="BedrijfActief", nullable=false)
    public boolean isBedrijfActief() {
        return this.bedrijfActief;
    }
    
    public void setBedrijfActief(boolean bedrijfActief) {
        this.bedrijfActief = bedrijfActief;
    }


    
    @Column(name="Telefoonnummer", length=15)
    public String getTelefoonnummer() {
        return this.telefoonnummer;
    }
    
    public void setTelefoonnummer(String telefoonnummer) {
        this.telefoonnummer = telefoonnummer;
    }





}


