package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * Bericht generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="Bericht")
@Table(name="Bericht"
)
public class Bericht  implements java.io.Serializable {


     private Integer berichtId;
     private String berichtNaam;
     private String fout;
     private String foutSoort;
     private Date datumTijd;

    public Bericht() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Bericht_ID", unique=true, nullable=false)
    public Integer getBerichtId() {
        return this.berichtId;
    }
    
    public void setBerichtId(Integer berichtId) {
        this.berichtId = berichtId;
    }


    
    @Column(name="BerichtNaam")
    public String getBerichtNaam() {
        return this.berichtNaam;
    }
    
    public void setBerichtNaam(String berichtNaam) {
        this.berichtNaam = berichtNaam;
    }


    
    @Column(name="Fout", nullable=false)
    public String getFout() {
        return this.fout;
    }
    
    public void setFout(String fout) {
        this.fout = fout;
    }


    
    @Column(name="FoutSoort", nullable=false, length=50)
    public String getFoutSoort() {
        return this.foutSoort;
    }
    
    public void setFoutSoort(String foutSoort) {
        this.foutSoort = foutSoort;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DatumTijd", nullable=false, length=19)
    public Date getDatumTijd() {
        return this.datumTijd;
    }
    
    public void setDatumTijd(Date datumTijd) {
        this.datumTijd = datumTijd;
    }





}


