package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * CIKvKBestuurder generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="CIKvKBestuurder")
@Table(name="CIKvKBestuurder"
    , uniqueConstraints = @UniqueConstraint(columnNames={"Naam", "CIKvKDossier_ID"}) 
)
public class CIKvKBestuurder  implements java.io.Serializable {


     private Integer cikvKbestuurderId;
     private CIKvKDossier CIKvKDossier;
     private String naam;
     private byte geslacht;
     private Set<CIKvKBestuurderFunctie> CIKvKBestuurderFuncties = new HashSet<CIKvKBestuurderFunctie>(0);

    public CIKvKBestuurder() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CIKvKBestuurder_ID", unique=true, nullable=false)
    public Integer getCikvKbestuurderId() {
        return this.cikvKbestuurderId;
    }
    
    public void setCikvKbestuurderId(Integer cikvKbestuurderId) {
        this.cikvKbestuurderId = cikvKbestuurderId;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CIKvKDossier_ID", nullable=false)
    public CIKvKDossier getCIKvKDossier() {
        return this.CIKvKDossier;
    }
    
    public void setCIKvKDossier(CIKvKDossier CIKvKDossier) {
        this.CIKvKDossier = CIKvKDossier;
    }



    @Transient
    public Integer getCIKvKDossierCikvKdossierId() {
        return this.CIKvKDossier == null ? null : this.CIKvKDossier.getCikvKdossierId();
    }

    public void setCIKvKDossierCikvKdossierId(Integer cikvKdossierId) {
        if (cikvKdossierId == null) {
            this.CIKvKDossier = null;
        } else {
            CIKvKDossier obj = new CIKvKDossier();
            obj.setCikvKdossierId(cikvKdossierId);
            this.CIKvKDossier = obj;
        }
    }


    
    @Column(name="Naam", nullable=false)
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }


    
    @Column(name="Geslacht", nullable=false)
    public byte getGeslacht() {
        return this.geslacht;
    }
    
    public void setGeslacht(byte geslacht) {
        this.geslacht = geslacht;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="CIKvKBestuurder")
    public Set<CIKvKBestuurderFunctie> getCIKvKBestuurderFuncties() {
        return this.CIKvKBestuurderFuncties;
    }
    
    public void setCIKvKBestuurderFuncties(Set<CIKvKBestuurderFunctie> CIKvKBestuurderFuncties) {
        this.CIKvKBestuurderFuncties = CIKvKBestuurderFuncties;
    }





}


