package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * CIKvKHistorieBestuurder generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="CIKvKHistorieBestuurder")
@Table(name="CIKvKHistorieBestuurder"
)
public class CIKvKHistorieBestuurder  implements java.io.Serializable {


     private Integer cikvKhistorieBestuurderId;
     private CIKvKDossierHistorie CIKvKDossierHistorie;
     private String naam;
     private byte geslacht;
     private Set<CIKvKHistorieBestuurderFunctie> CIKvKHistorieBestuurderFuncties = new HashSet<CIKvKHistorieBestuurderFunctie>(0);

    public CIKvKHistorieBestuurder() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CIKvKHistorieBestuurder_ID", unique=true, nullable=false)
    public Integer getCikvKhistorieBestuurderId() {
        return this.cikvKhistorieBestuurderId;
    }
    
    public void setCikvKhistorieBestuurderId(Integer cikvKhistorieBestuurderId) {
        this.cikvKhistorieBestuurderId = cikvKhistorieBestuurderId;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CIKvKDossierHistorie_ID", nullable=false)
    public CIKvKDossierHistorie getCIKvKDossierHistorie() {
        return this.CIKvKDossierHistorie;
    }
    
    public void setCIKvKDossierHistorie(CIKvKDossierHistorie CIKvKDossierHistorie) {
        this.CIKvKDossierHistorie = CIKvKDossierHistorie;
    }



    @Transient
    public Integer getCIKvKDossierHistorieCikvKdossierHistorieId() {
        return this.CIKvKDossierHistorie == null ? null : this.CIKvKDossierHistorie.getCikvKdossierHistorieId();
    }

    public void setCIKvKDossierHistorieCikvKdossierHistorieId(Integer cikvKdossierHistorieId) {
        if (cikvKdossierHistorieId == null) {
            this.CIKvKDossierHistorie = null;
        } else {
            CIKvKDossierHistorie obj = new CIKvKDossierHistorie();
            obj.setCikvKdossierHistorieId(cikvKdossierHistorieId);
            this.CIKvKDossierHistorie = obj;
        }
    }


    
    @Column(name="Naam", nullable=false)
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }


    
    @Column(name="Geslacht", nullable=false)
    public byte getGeslacht() {
        return this.geslacht;
    }
    
    public void setGeslacht(byte geslacht) {
        this.geslacht = geslacht;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="CIKvKHistorieBestuurder")
    public Set<CIKvKHistorieBestuurderFunctie> getCIKvKHistorieBestuurderFuncties() {
        return this.CIKvKHistorieBestuurderFuncties;
    }
    
    public void setCIKvKHistorieBestuurderFuncties(Set<CIKvKHistorieBestuurderFunctie> CIKvKHistorieBestuurderFuncties) {
        this.CIKvKHistorieBestuurderFuncties = CIKvKHistorieBestuurderFuncties;
    }





}


