package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * CIKvKCurator generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="CIKvKCurator")
@Table(name="CIKvKCurator"
)
public class CIKvKCurator  implements java.io.Serializable {


     private Integer cikvKcuratorId;
     private CIKvKDossier CIKvKDossier;
     private String naam;
     private String adres;

    public CIKvKCurator() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CIKvKCurator_ID", unique=true, nullable=false)
    public Integer getCikvKcuratorId() {
        return this.cikvKcuratorId;
    }
    
    public void setCikvKcuratorId(Integer cikvKcuratorId) {
        this.cikvKcuratorId = cikvKcuratorId;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CIKvKDossier_ID", nullable=false)
    public CIKvKDossier getCIKvKDossier() {
        return this.CIKvKDossier;
    }
    
    public void setCIKvKDossier(CIKvKDossier CIKvKDossier) {
        this.CIKvKDossier = CIKvKDossier;
    }



    @Transient
    public Integer getCIKvKDossierCikvKdossierId() {
        return this.CIKvKDossier == null ? null : this.CIKvKDossier.getCikvKdossierId();
    }

    public void setCIKvKDossierCikvKdossierId(Integer cikvKdossierId) {
        if (cikvKdossierId == null) {
            this.CIKvKDossier = null;
        } else {
            CIKvKDossier obj = new CIKvKDossier();
            obj.setCikvKdossierId(cikvKdossierId);
            this.CIKvKDossier = obj;
        }
    }


    
    @Column(name="Naam", nullable=false)
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }


    
    @Column(name="Adres", nullable=false, length=1000)
    public String getAdres() {
        return this.adres;
    }
    
    public void setAdres(String adres) {
        this.adres = adres;
    }





}


