package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * CIKvKHistorieBestuurderFunctie generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="CIKvKHistorieBestuurderFunctie")
@Table(name="CIKvKHistorieBestuurderFunctie"
)
public class CIKvKHistorieBestuurderFunctie  implements java.io.Serializable {


     private Integer cikvKhistorieBestuurderFunctieId;
     private CIKvKHistorieBestuurder CIKvKHistorieBestuurder;
     private String functie;

    public CIKvKHistorieBestuurderFunctie() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CIKvKHistorieBestuurderFunctie_ID", unique=true, nullable=false)
    public Integer getCikvKhistorieBestuurderFunctieId() {
        return this.cikvKhistorieBestuurderFunctieId;
    }
    
    public void setCikvKhistorieBestuurderFunctieId(Integer cikvKhistorieBestuurderFunctieId) {
        this.cikvKhistorieBestuurderFunctieId = cikvKhistorieBestuurderFunctieId;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CIKvKHistorieBestuurder_ID", nullable=false)
    public CIKvKHistorieBestuurder getCIKvKHistorieBestuurder() {
        return this.CIKvKHistorieBestuurder;
    }
    
    public void setCIKvKHistorieBestuurder(CIKvKHistorieBestuurder CIKvKHistorieBestuurder) {
        this.CIKvKHistorieBestuurder = CIKvKHistorieBestuurder;
    }



    @Transient
    public Integer getCIKvKHistorieBestuurderCikvKhistorieBestuurderId() {
        return this.CIKvKHistorieBestuurder == null ? null : this.CIKvKHistorieBestuurder.getCikvKhistorieBestuurderId();
    }

    public void setCIKvKHistorieBestuurderCikvKhistorieBestuurderId(Integer cikvKhistorieBestuurderId) {
        if (cikvKhistorieBestuurderId == null) {
            this.CIKvKHistorieBestuurder = null;
        } else {
            CIKvKHistorieBestuurder obj = new CIKvKHistorieBestuurder();
            obj.setCikvKhistorieBestuurderId(cikvKhistorieBestuurderId);
            this.CIKvKHistorieBestuurder = obj;
        }
    }


    
    @Column(name="Functie", nullable=false)
    public String getFunctie() {
        return this.functie;
    }
    
    public void setFunctie(String functie) {
        this.functie = functie;
    }





}


