package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * CIKvKDossierHistorie generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="CIKvKDossierHistorie")
@Table(name="CIKvKDossierHistorie"
)
public class CIKvKDossierHistorie  implements java.io.Serializable {


     private Integer cikvKdossierHistorieId;
     private CIKvKDossier CIKvKDossier;
     private Date datumLaatsteUpdate;
     private String kvKnummer;
     private Integer nrDochters;
     private String aanvangFaillissement;
     private String aanvangSurseance;
     private String beherendKn;
     private String continent;
     private String continentCode;
     private Date datumInschrijving;
     private Date datumOntbinding;
     private Date datumOpheffing;
     private Date datumUitschrijving;
     private Date datumVoortzetting;
     private Integer deponeringJaarstukken;
     private String domeinNaam;
     private String dossierNr;
     private String ecoAct;
     private String eindeFaillissement;
     private String eindeSurseance;
     private String export;
     private String fc;
     private String gemeente;
     private String handelsNaam;
     private String hn1x2x30;
     private String hn1x30;
     private String hn1x45;
     private String hn2x2x30;
     private String hoofdActiviteit;
     private String hoofdNeven;
     private String huisnummerCa;
     private String huisnummer;
     private String import_;
     private String indicatieFaillissement;
     private String indicatieSurseance;
     private String land;
     private String landCode;
     private String telefoonNummerMobiel;
     private String nevenActiviteit1;
     private String nevenActiviteit2;
     private String postcodeCa;
     private String postcode;
     private String provincie;
     private String redenOpheffing;
     private String redenUitschrijving;
     private String rsin;
     private String rv;
     private String sbihoofdAct;
     private String sbinevenActiviteit1;
     private String sbinevenActiviteit2;
     private String soortOntbinding;
     private String straat;
     private String straatHuisnummerCa;
     private String straatHuisnummer;
     private String straatCa;
     private String subDossier;
     private String telefoonAbonneeNummer;
     private String telefoonNetNummer;
     private String huisnummerToevoegingCa;
     private String huisnummerToevoeging;
     private String venNaam;
     private String vestigingsNummer;
     private String vsi;
     private Integer wkpTot;
     private String plaats;
     private String plaatsCa;
     private String turnover;
     private String profit;
     private Integer nrEmployees;
     private String ciSbi1;
     private String ciSbi2;
     private String ciSbi3;
     private String parent;
     private String ultimateParent;
     private String creditSafeId;
     private Date datumHuidigeVestiging;
     private Long gestortKapitaal;
     private Long nominaalAandelenKapitaal;
     private Set<CIKvKHistorieBestuurder> CIKvKHistorieBestuurders = new HashSet<CIKvKHistorieBestuurder>(0);
     private Set<CIKvKHistorieAandeelhouder> CIKvKHistorieAandeelhouders = new HashSet<CIKvKHistorieAandeelhouder>(0);
     private Set<CIKvKHistorieCurator> CIKvKHistorieCurators = new HashSet<CIKvKHistorieCurator>(0);

    public CIKvKDossierHistorie() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CIKvKDossierHistorie_ID", unique=true, nullable=false)
    public Integer getCikvKdossierHistorieId() {
        return this.cikvKdossierHistorieId;
    }
    
    public void setCikvKdossierHistorieId(Integer cikvKdossierHistorieId) {
        this.cikvKdossierHistorieId = cikvKdossierHistorieId;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CIKvKDossier_ID")
    public CIKvKDossier getCIKvKDossier() {
        return this.CIKvKDossier;
    }
    
    public void setCIKvKDossier(CIKvKDossier CIKvKDossier) {
        this.CIKvKDossier = CIKvKDossier;
    }



    @Transient
    public Integer getCIKvKDossierCikvKdossierId() {
        return this.CIKvKDossier == null ? null : this.CIKvKDossier.getCikvKdossierId();
    }

    public void setCIKvKDossierCikvKdossierId(Integer cikvKdossierId) {
        if (cikvKdossierId == null) {
            this.CIKvKDossier = null;
        } else {
            CIKvKDossier obj = new CIKvKDossier();
            obj.setCikvKdossierId(cikvKdossierId);
            this.CIKvKDossier = obj;
        }
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.DATE)
    @Column(name="DatumLaatsteUpdate", nullable=false, length=10)
    public Date getDatumLaatsteUpdate() {
        return this.datumLaatsteUpdate;
    }
    
    public void setDatumLaatsteUpdate(Date datumLaatsteUpdate) {
        this.datumLaatsteUpdate = datumLaatsteUpdate;
    }


    
    @Column(name="KvKNummer", nullable=false, length=20)
    public String getKvKnummer() {
        return this.kvKnummer;
    }
    
    public void setKvKnummer(String kvKnummer) {
        this.kvKnummer = kvKnummer;
    }


    
    @Column(name="NrDochters")
    public Integer getNrDochters() {
        return this.nrDochters;
    }
    
    public void setNrDochters(Integer nrDochters) {
        this.nrDochters = nrDochters;
    }


    
    @Column(name="AanvangFaillissement", length=100)
    public String getAanvangFaillissement() {
        return this.aanvangFaillissement;
    }
    
    public void setAanvangFaillissement(String aanvangFaillissement) {
        this.aanvangFaillissement = aanvangFaillissement;
    }


    
    @Column(name="AanvangSurseance", length=100)
    public String getAanvangSurseance() {
        return this.aanvangSurseance;
    }
    
    public void setAanvangSurseance(String aanvangSurseance) {
        this.aanvangSurseance = aanvangSurseance;
    }


    
    @Column(name="BeherendKN")
    public String getBeherendKn() {
        return this.beherendKn;
    }
    
    public void setBeherendKn(String beherendKn) {
        this.beherendKn = beherendKn;
    }


    
    @Column(name="Continent")
    public String getContinent() {
        return this.continent;
    }
    
    public void setContinent(String continent) {
        this.continent = continent;
    }


    
    @Column(name="ContinentCode", length=50)
    public String getContinentCode() {
        return this.continentCode;
    }
    
    public void setContinentCode(String continentCode) {
        this.continentCode = continentCode;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.DATE)
    @Column(name="DatumInschrijving", length=10)
    public Date getDatumInschrijving() {
        return this.datumInschrijving;
    }
    
    public void setDatumInschrijving(Date datumInschrijving) {
        this.datumInschrijving = datumInschrijving;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.DATE)
    @Column(name="DatumOntbinding", length=10)
    public Date getDatumOntbinding() {
        return this.datumOntbinding;
    }
    
    public void setDatumOntbinding(Date datumOntbinding) {
        this.datumOntbinding = datumOntbinding;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.DATE)
    @Column(name="DatumOpheffing", length=10)
    public Date getDatumOpheffing() {
        return this.datumOpheffing;
    }
    
    public void setDatumOpheffing(Date datumOpheffing) {
        this.datumOpheffing = datumOpheffing;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.DATE)
    @Column(name="DatumUitschrijving", length=10)
    public Date getDatumUitschrijving() {
        return this.datumUitschrijving;
    }
    
    public void setDatumUitschrijving(Date datumUitschrijving) {
        this.datumUitschrijving = datumUitschrijving;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.DATE)
    @Column(name="DatumVoortzetting", length=10)
    public Date getDatumVoortzetting() {
        return this.datumVoortzetting;
    }
    
    public void setDatumVoortzetting(Date datumVoortzetting) {
        this.datumVoortzetting = datumVoortzetting;
    }


    
    @Column(name="DeponeringJaarstukken")
    public Integer getDeponeringJaarstukken() {
        return this.deponeringJaarstukken;
    }
    
    public void setDeponeringJaarstukken(Integer deponeringJaarstukken) {
        this.deponeringJaarstukken = deponeringJaarstukken;
    }


    
    @Column(name="DomeinNaam", length=50)
    public String getDomeinNaam() {
        return this.domeinNaam;
    }
    
    public void setDomeinNaam(String domeinNaam) {
        this.domeinNaam = domeinNaam;
    }


    
    @Column(name="DossierNr", length=50)
    public String getDossierNr() {
        return this.dossierNr;
    }
    
    public void setDossierNr(String dossierNr) {
        this.dossierNr = dossierNr;
    }


    
    @Column(name="EcoAct", length=50)
    public String getEcoAct() {
        return this.ecoAct;
    }
    
    public void setEcoAct(String ecoAct) {
        this.ecoAct = ecoAct;
    }


    
    @Column(name="EindeFaillissement", length=100)
    public String getEindeFaillissement() {
        return this.eindeFaillissement;
    }
    
    public void setEindeFaillissement(String eindeFaillissement) {
        this.eindeFaillissement = eindeFaillissement;
    }


    
    @Column(name="EindeSurseance", length=100)
    public String getEindeSurseance() {
        return this.eindeSurseance;
    }
    
    public void setEindeSurseance(String eindeSurseance) {
        this.eindeSurseance = eindeSurseance;
    }


    
    @Column(name="Export")
    public String getExport() {
        return this.export;
    }
    
    public void setExport(String export) {
        this.export = export;
    }


    
    @Column(name="FC")
    public String getFc() {
        return this.fc;
    }
    
    public void setFc(String fc) {
        this.fc = fc;
    }


    
    @Column(name="Gemeente", length=100)
    public String getGemeente() {
        return this.gemeente;
    }
    
    public void setGemeente(String gemeente) {
        this.gemeente = gemeente;
    }


    
    @Column(name="HandelsNaam")
    public String getHandelsNaam() {
        return this.handelsNaam;
    }
    
    public void setHandelsNaam(String handelsNaam) {
        this.handelsNaam = handelsNaam;
    }


    
    @Column(name="HN_1x2x30", length=50)
    public String getHn1x2x30() {
        return this.hn1x2x30;
    }
    
    public void setHn1x2x30(String hn1x2x30) {
        this.hn1x2x30 = hn1x2x30;
    }


    
    @Column(name="HN_1x30", length=50)
    public String getHn1x30() {
        return this.hn1x30;
    }
    
    public void setHn1x30(String hn1x30) {
        this.hn1x30 = hn1x30;
    }


    
    @Column(name="HN_1x45", length=50)
    public String getHn1x45() {
        return this.hn1x45;
    }
    
    public void setHn1x45(String hn1x45) {
        this.hn1x45 = hn1x45;
    }


    
    @Column(name="HN_2x2x30", length=50)
    public String getHn2x2x30() {
        return this.hn2x2x30;
    }
    
    public void setHn2x2x30(String hn2x2x30) {
        this.hn2x2x30 = hn2x2x30;
    }


    
    @Column(name="HoofdActiviteit")
    public String getHoofdActiviteit() {
        return this.hoofdActiviteit;
    }
    
    public void setHoofdActiviteit(String hoofdActiviteit) {
        this.hoofdActiviteit = hoofdActiviteit;
    }


    
    @Column(name="HoofdNeven")
    public String getHoofdNeven() {
        return this.hoofdNeven;
    }
    
    public void setHoofdNeven(String hoofdNeven) {
        this.hoofdNeven = hoofdNeven;
    }


    
    @Column(name="Huisnummer_CA", length=50)
    public String getHuisnummerCa() {
        return this.huisnummerCa;
    }
    
    public void setHuisnummerCa(String huisnummerCa) {
        this.huisnummerCa = huisnummerCa;
    }


    
    @Column(name="Huisnummer", length=50)
    public String getHuisnummer() {
        return this.huisnummer;
    }
    
    public void setHuisnummer(String huisnummer) {
        this.huisnummer = huisnummer;
    }


    
    @Column(name="Import")
    public String getImport_() {
        return this.import_;
    }
    
    public void setImport_(String import_) {
        this.import_ = import_;
    }


    
    @Column(name="IndicatieFaillissement", length=50)
    public String getIndicatieFaillissement() {
        return this.indicatieFaillissement;
    }
    
    public void setIndicatieFaillissement(String indicatieFaillissement) {
        this.indicatieFaillissement = indicatieFaillissement;
    }


    
    @Column(name="IndicatieSurseance", length=50)
    public String getIndicatieSurseance() {
        return this.indicatieSurseance;
    }
    
    public void setIndicatieSurseance(String indicatieSurseance) {
        this.indicatieSurseance = indicatieSurseance;
    }


    
    @Column(name="Land")
    public String getLand() {
        return this.land;
    }
    
    public void setLand(String land) {
        this.land = land;
    }


    
    @Column(name="LandCode", length=50)
    public String getLandCode() {
        return this.landCode;
    }
    
    public void setLandCode(String landCode) {
        this.landCode = landCode;
    }


    
    @Column(name="TelefoonNummerMobiel", length=15)
    public String getTelefoonNummerMobiel() {
        return this.telefoonNummerMobiel;
    }
    
    public void setTelefoonNummerMobiel(String telefoonNummerMobiel) {
        this.telefoonNummerMobiel = telefoonNummerMobiel;
    }


    
    @Column(name="NevenActiviteit1")
    public String getNevenActiviteit1() {
        return this.nevenActiviteit1;
    }
    
    public void setNevenActiviteit1(String nevenActiviteit1) {
        this.nevenActiviteit1 = nevenActiviteit1;
    }


    
    @Column(name="NevenActiviteit2")
    public String getNevenActiviteit2() {
        return this.nevenActiviteit2;
    }
    
    public void setNevenActiviteit2(String nevenActiviteit2) {
        this.nevenActiviteit2 = nevenActiviteit2;
    }


    
    @Column(name="Postcode_CA", length=7)
    public String getPostcodeCa() {
        return this.postcodeCa;
    }
    
    public void setPostcodeCa(String postcodeCa) {
        this.postcodeCa = postcodeCa;
    }


    
    @Column(name="Postcode", length=7)
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }


    
    @Column(name="Provincie", length=100)
    public String getProvincie() {
        return this.provincie;
    }
    
    public void setProvincie(String provincie) {
        this.provincie = provincie;
    }


    
    @Column(name="RedenOpheffing")
    public String getRedenOpheffing() {
        return this.redenOpheffing;
    }
    
    public void setRedenOpheffing(String redenOpheffing) {
        this.redenOpheffing = redenOpheffing;
    }


    
    @Column(name="RedenUitschrijving")
    public String getRedenUitschrijving() {
        return this.redenUitschrijving;
    }
    
    public void setRedenUitschrijving(String redenUitschrijving) {
        this.redenUitschrijving = redenUitschrijving;
    }


    
    @Column(name="RSIN")
    public String getRsin() {
        return this.rsin;
    }
    
    public void setRsin(String rsin) {
        this.rsin = rsin;
    }


    
    @Column(name="RV")
    public String getRv() {
        return this.rv;
    }
    
    public void setRv(String rv) {
        this.rv = rv;
    }


    
    @Column(name="SBIHoofdAct")
    public String getSbihoofdAct() {
        return this.sbihoofdAct;
    }
    
    public void setSbihoofdAct(String sbihoofdAct) {
        this.sbihoofdAct = sbihoofdAct;
    }


    
    @Column(name="SBINevenActiviteit1")
    public String getSbinevenActiviteit1() {
        return this.sbinevenActiviteit1;
    }
    
    public void setSbinevenActiviteit1(String sbinevenActiviteit1) {
        this.sbinevenActiviteit1 = sbinevenActiviteit1;
    }


    
    @Column(name="SBINevenActiviteit2")
    public String getSbinevenActiviteit2() {
        return this.sbinevenActiviteit2;
    }
    
    public void setSbinevenActiviteit2(String sbinevenActiviteit2) {
        this.sbinevenActiviteit2 = sbinevenActiviteit2;
    }


    
    @Column(name="SoortOntbinding")
    public String getSoortOntbinding() {
        return this.soortOntbinding;
    }
    
    public void setSoortOntbinding(String soortOntbinding) {
        this.soortOntbinding = soortOntbinding;
    }


    
    @Column(name="Straat", length=100)
    public String getStraat() {
        return this.straat;
    }
    
    public void setStraat(String straat) {
        this.straat = straat;
    }


    
    @Column(name="Straat_Huisnummer_CA", length=100)
    public String getStraatHuisnummerCa() {
        return this.straatHuisnummerCa;
    }
    
    public void setStraatHuisnummerCa(String straatHuisnummerCa) {
        this.straatHuisnummerCa = straatHuisnummerCa;
    }


    
    @Column(name="Straat_Huisnummer", length=100)
    public String getStraatHuisnummer() {
        return this.straatHuisnummer;
    }
    
    public void setStraatHuisnummer(String straatHuisnummer) {
        this.straatHuisnummer = straatHuisnummer;
    }


    
    @Column(name="Straat_CA", length=100)
    public String getStraatCa() {
        return this.straatCa;
    }
    
    public void setStraatCa(String straatCa) {
        this.straatCa = straatCa;
    }


    
    @Column(name="SubDossier")
    public String getSubDossier() {
        return this.subDossier;
    }
    
    public void setSubDossier(String subDossier) {
        this.subDossier = subDossier;
    }


    
    @Column(name="TelefoonAbonneeNummer", length=15)
    public String getTelefoonAbonneeNummer() {
        return this.telefoonAbonneeNummer;
    }
    
    public void setTelefoonAbonneeNummer(String telefoonAbonneeNummer) {
        this.telefoonAbonneeNummer = telefoonAbonneeNummer;
    }


    
    @Column(name="TelefoonNetNummer", length=15)
    public String getTelefoonNetNummer() {
        return this.telefoonNetNummer;
    }
    
    public void setTelefoonNetNummer(String telefoonNetNummer) {
        this.telefoonNetNummer = telefoonNetNummer;
    }


    
    @Column(name="HuisnummerToevoeging_CA", length=35)
    public String getHuisnummerToevoegingCa() {
        return this.huisnummerToevoegingCa;
    }
    
    public void setHuisnummerToevoegingCa(String huisnummerToevoegingCa) {
        this.huisnummerToevoegingCa = huisnummerToevoegingCa;
    }


    
    @Column(name="HuisnummerToevoeging", length=35)
    public String getHuisnummerToevoeging() {
        return this.huisnummerToevoeging;
    }
    
    public void setHuisnummerToevoeging(String huisnummerToevoeging) {
        this.huisnummerToevoeging = huisnummerToevoeging;
    }


    
    @Column(name="VenNaam")
    public String getVenNaam() {
        return this.venNaam;
    }
    
    public void setVenNaam(String venNaam) {
        this.venNaam = venNaam;
    }


    
    @Column(name="VestigingsNummer", length=50)
    public String getVestigingsNummer() {
        return this.vestigingsNummer;
    }
    
    public void setVestigingsNummer(String vestigingsNummer) {
        this.vestigingsNummer = vestigingsNummer;
    }


    
    @Column(name="VSI", length=100)
    public String getVsi() {
        return this.vsi;
    }
    
    public void setVsi(String vsi) {
        this.vsi = vsi;
    }


    
    @Column(name="WKP_Tot")
    public Integer getWkpTot() {
        return this.wkpTot;
    }
    
    public void setWkpTot(Integer wkpTot) {
        this.wkpTot = wkpTot;
    }


    
    @Column(name="Plaats", length=100)
    public String getPlaats() {
        return this.plaats;
    }
    
    public void setPlaats(String plaats) {
        this.plaats = plaats;
    }


    
    @Column(name="Plaats_CA", length=100)
    public String getPlaatsCa() {
        return this.plaatsCa;
    }
    
    public void setPlaatsCa(String plaatsCa) {
        this.plaatsCa = plaatsCa;
    }


    
    @Column(name="Turnover", length=100)
    public String getTurnover() {
        return this.turnover;
    }
    
    public void setTurnover(String turnover) {
        this.turnover = turnover;
    }


    
    @Column(name="Profit", length=100)
    public String getProfit() {
        return this.profit;
    }
    
    public void setProfit(String profit) {
        this.profit = profit;
    }


    
    @Column(name="NrEmployees")
    public Integer getNrEmployees() {
        return this.nrEmployees;
    }
    
    public void setNrEmployees(Integer nrEmployees) {
        this.nrEmployees = nrEmployees;
    }


    
    @Column(name="CI_SBI1", length=100)
    public String getCiSbi1() {
        return this.ciSbi1;
    }
    
    public void setCiSbi1(String ciSbi1) {
        this.ciSbi1 = ciSbi1;
    }


    
    @Column(name="CI_SBI2", length=100)
    public String getCiSbi2() {
        return this.ciSbi2;
    }
    
    public void setCiSbi2(String ciSbi2) {
        this.ciSbi2 = ciSbi2;
    }


    
    @Column(name="CI_SBI3", length=100)
    public String getCiSbi3() {
        return this.ciSbi3;
    }
    
    public void setCiSbi3(String ciSbi3) {
        this.ciSbi3 = ciSbi3;
    }


    
    @Column(name="Parent", length=100)
    public String getParent() {
        return this.parent;
    }
    
    public void setParent(String parent) {
        this.parent = parent;
    }


    
    @Column(name="UltimateParent", length=100)
    public String getUltimateParent() {
        return this.ultimateParent;
    }
    
    public void setUltimateParent(String ultimateParent) {
        this.ultimateParent = ultimateParent;
    }


    
    @Column(name="CreditSafeId", length=20)
    public String getCreditSafeId() {
        return this.creditSafeId;
    }
    
    public void setCreditSafeId(String creditSafeId) {
        this.creditSafeId = creditSafeId;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.DATE)
    @Column(name="DatumHuidigeVestiging", length=10)
    public Date getDatumHuidigeVestiging() {
        return this.datumHuidigeVestiging;
    }
    
    public void setDatumHuidigeVestiging(Date datumHuidigeVestiging) {
        this.datumHuidigeVestiging = datumHuidigeVestiging;
    }


    
    @Column(name="GestortKapitaal")
    public Long getGestortKapitaal() {
        return this.gestortKapitaal;
    }
    
    public void setGestortKapitaal(Long gestortKapitaal) {
        this.gestortKapitaal = gestortKapitaal;
    }


    
    @Column(name="NominaalAandelenKapitaal")
    public Long getNominaalAandelenKapitaal() {
        return this.nominaalAandelenKapitaal;
    }
    
    public void setNominaalAandelenKapitaal(Long nominaalAandelenKapitaal) {
        this.nominaalAandelenKapitaal = nominaalAandelenKapitaal;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="CIKvKDossierHistorie")
    public Set<CIKvKHistorieBestuurder> getCIKvKHistorieBestuurders() {
        return this.CIKvKHistorieBestuurders;
    }
    
    public void setCIKvKHistorieBestuurders(Set<CIKvKHistorieBestuurder> CIKvKHistorieBestuurders) {
        this.CIKvKHistorieBestuurders = CIKvKHistorieBestuurders;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="CIKvKDossierHistorie")
    public Set<CIKvKHistorieAandeelhouder> getCIKvKHistorieAandeelhouders() {
        return this.CIKvKHistorieAandeelhouders;
    }
    
    public void setCIKvKHistorieAandeelhouders(Set<CIKvKHistorieAandeelhouder> CIKvKHistorieAandeelhouders) {
        this.CIKvKHistorieAandeelhouders = CIKvKHistorieAandeelhouders;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="CIKvKDossierHistorie")
    public Set<CIKvKHistorieCurator> getCIKvKHistorieCurators() {
        return this.CIKvKHistorieCurators;
    }
    
    public void setCIKvKHistorieCurators(Set<CIKvKHistorieCurator> CIKvKHistorieCurators) {
        this.CIKvKHistorieCurators = CIKvKHistorieCurators;
    }





}


