package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * CIKvKAandeelhouder generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="CIKvKAandeelhouder")
@Table(name="CIKvKAandeelhouder"
    , uniqueConstraints = @UniqueConstraint(columnNames={"CIKvKDossier_ID", "Naam"}) 
)
public class CIKvKAandeelhouder  implements java.io.Serializable {


     private Integer cikvKaandeelhouderId;
     private CIKvKDossier CIKvKDossier;
     private String naam;
     private String straat;
     private String huisnummer;
     private String huisnummerToevoeging;
     private String postcode;
     private String plaats;
     private Double aandelenPercentage;

    public CIKvKAandeelhouder() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CIKvKAandeelhouder_ID", unique=true, nullable=false)
    public Integer getCikvKaandeelhouderId() {
        return this.cikvKaandeelhouderId;
    }
    
    public void setCikvKaandeelhouderId(Integer cikvKaandeelhouderId) {
        this.cikvKaandeelhouderId = cikvKaandeelhouderId;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CIKvKDossier_ID", nullable=false)
    public CIKvKDossier getCIKvKDossier() {
        return this.CIKvKDossier;
    }
    
    public void setCIKvKDossier(CIKvKDossier CIKvKDossier) {
        this.CIKvKDossier = CIKvKDossier;
    }



    @Transient
    public Integer getCIKvKDossierCikvKdossierId() {
        return this.CIKvKDossier == null ? null : this.CIKvKDossier.getCikvKdossierId();
    }

    public void setCIKvKDossierCikvKdossierId(Integer cikvKdossierId) {
        if (cikvKdossierId == null) {
            this.CIKvKDossier = null;
        } else {
            CIKvKDossier obj = new CIKvKDossier();
            obj.setCikvKdossierId(cikvKdossierId);
            this.CIKvKDossier = obj;
        }
    }


    
    @Column(name="Naam", nullable=false)
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }


    
    @Column(name="Straat", length=100)
    public String getStraat() {
        return this.straat;
    }
    
    public void setStraat(String straat) {
        this.straat = straat;
    }


    
    @Column(name="Huisnummer", length=50)
    public String getHuisnummer() {
        return this.huisnummer;
    }
    
    public void setHuisnummer(String huisnummer) {
        this.huisnummer = huisnummer;
    }


    
    @Column(name="HuisnummerToevoeging", length=10)
    public String getHuisnummerToevoeging() {
        return this.huisnummerToevoeging;
    }
    
    public void setHuisnummerToevoeging(String huisnummerToevoeging) {
        this.huisnummerToevoeging = huisnummerToevoeging;
    }


    
    @Column(name="Postcode", length=7)
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }


    
    @Column(name="Plaats", length=100)
    public String getPlaats() {
        return this.plaats;
    }
    
    public void setPlaats(String plaats) {
        this.plaats = plaats;
    }


    
    @Column(name="AandelenPercentage", precision=5)
    public Double getAandelenPercentage() {
        return this.aandelenPercentage;
    }
    
    public void setAandelenPercentage(Double aandelenPercentage) {
        this.aandelenPercentage = aandelenPercentage;
    }





}


