package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * CompanyInfo generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="CompanyInfo")
@Table(name="CompanyInfo"
)
public class CompanyInfo  implements java.io.Serializable {


     private Integer companyInfoId;
     private String kvKnummer;
     private String bedrijfsNaam;
     private String kvKnummerVerkort;
     private String sub;
     private String straat;
     private String huisNummer;
     private String postcode;
     private String plaats;
     private String type;
     private String status;
     private String website;
     private String vestiging;
     private String rechtsvorm;
     private Date datumAnbi;
     private Date datumLaatsteUpdate;
     private String creditSafeId;
     private String creditSafeHeadQuarters;
     private String companyInfocol;
     private String creditSafeStatus;

    public CompanyInfo() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CompanyInfo_ID", unique=true, nullable=false)
    public Integer getCompanyInfoId() {
        return this.companyInfoId;
    }
    
    public void setCompanyInfoId(Integer companyInfoId) {
        this.companyInfoId = companyInfoId;
    }


    
    @Column(name="KvKNummer", nullable=false, length=20)
    public String getKvKnummer() {
        return this.kvKnummer;
    }
    
    public void setKvKnummer(String kvKnummer) {
        this.kvKnummer = kvKnummer;
    }


    
    @Column(name="BedrijfsNaam", length=50)
    public String getBedrijfsNaam() {
        return this.bedrijfsNaam;
    }
    
    public void setBedrijfsNaam(String bedrijfsNaam) {
        this.bedrijfsNaam = bedrijfsNaam;
    }


    
    @Column(name="KvKNummerVerkort", length=10)
    public String getKvKnummerVerkort() {
        return this.kvKnummerVerkort;
    }
    
    public void setKvKnummerVerkort(String kvKnummerVerkort) {
        this.kvKnummerVerkort = kvKnummerVerkort;
    }


    
    @Column(name="Sub", length=10)
    public String getSub() {
        return this.sub;
    }
    
    public void setSub(String sub) {
        this.sub = sub;
    }


    
    @Column(name="Straat", length=35)
    public String getStraat() {
        return this.straat;
    }
    
    public void setStraat(String straat) {
        this.straat = straat;
    }


    
    @Column(name="HuisNummer", length=10)
    public String getHuisNummer() {
        return this.huisNummer;
    }
    
    public void setHuisNummer(String huisNummer) {
        this.huisNummer = huisNummer;
    }


    
    @Column(name="Postcode", length=7)
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }


    
    @Column(name="Plaats", length=24)
    public String getPlaats() {
        return this.plaats;
    }
    
    public void setPlaats(String plaats) {
        this.plaats = plaats;
    }


    
    @Column(name="Type", length=50)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }


    
    @Column(name="Status", length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }


    
    @Column(name="Website", length=100)
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }


    
    @Column(name="Vestiging", length=20)
    public String getVestiging() {
        return this.vestiging;
    }
    
    public void setVestiging(String vestiging) {
        this.vestiging = vestiging;
    }


    
    @Column(name="Rechtsvorm", length=50)
    public String getRechtsvorm() {
        return this.rechtsvorm;
    }
    
    public void setRechtsvorm(String rechtsvorm) {
        this.rechtsvorm = rechtsvorm;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.DATE)
    @Column(name="DatumAnbi", length=10)
    public Date getDatumAnbi() {
        return this.datumAnbi;
    }
    
    public void setDatumAnbi(Date datumAnbi) {
        this.datumAnbi = datumAnbi;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.DATE)
    @Column(name="DatumLaatsteUpdate", length=10)
    public Date getDatumLaatsteUpdate() {
        return this.datumLaatsteUpdate;
    }
    
    public void setDatumLaatsteUpdate(Date datumLaatsteUpdate) {
        this.datumLaatsteUpdate = datumLaatsteUpdate;
    }


    
    @Column(name="CreditSafeId", length=20)
    public String getCreditSafeId() {
        return this.creditSafeId;
    }
    
    public void setCreditSafeId(String creditSafeId) {
        this.creditSafeId = creditSafeId;
    }


    
    @Column(name="CreditSafeHeadQuarters", length=1)
    public String getCreditSafeHeadQuarters() {
        return this.creditSafeHeadQuarters;
    }
    
    public void setCreditSafeHeadQuarters(String creditSafeHeadQuarters) {
        this.creditSafeHeadQuarters = creditSafeHeadQuarters;
    }


    
    @Column(name="CompanyInfocol", length=45)
    public String getCompanyInfocol() {
        return this.companyInfocol;
    }
    
    public void setCompanyInfocol(String companyInfocol) {
        this.companyInfocol = companyInfocol;
    }


    
    @Column(name="CreditSafeStatus", length=20)
    public String getCreditSafeStatus() {
        return this.creditSafeStatus;
    }
    
    public void setCreditSafeStatus(String creditSafeStatus) {
        this.creditSafeStatus = creditSafeStatus;
    }





}


