package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * Configuratie generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="Configuratie")
@Table(name="Configuratie"
)
public class Configuratie  implements java.io.Serializable {


     private String code;
     private String omschrijving;
     private Integer waardeInt;
     private Boolean indTonen;
     private Boolean waardeBool;
     private Date waardeDate;
     private String waardeString;

    public Configuratie() {
    }

   
     @Id 

    
    @Column(name="Code", unique=true, nullable=false, length=50)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }


    
    @Column(name="Omschrijving", nullable=false, length=60)
    public String getOmschrijving() {
        return this.omschrijving;
    }
    
    public void setOmschrijving(String omschrijving) {
        this.omschrijving = omschrijving;
    }


    
    @Column(name="Waarde_int")
    public Integer getWaardeInt() {
        return this.waardeInt;
    }
    
    public void setWaardeInt(Integer waardeInt) {
        this.waardeInt = waardeInt;
    }


    
    @Column(name="IndTonen")
    public Boolean getIndTonen() {
        return this.indTonen;
    }
    
    public void setIndTonen(Boolean indTonen) {
        this.indTonen = indTonen;
    }


    
    @Column(name="Waarde_bool")
    public Boolean getWaardeBool() {
        return this.waardeBool;
    }
    
    public void setWaardeBool(Boolean waardeBool) {
        this.waardeBool = waardeBool;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Waarde_date", length=19)
    public Date getWaardeDate() {
        return this.waardeDate;
    }
    
    public void setWaardeDate(Date waardeDate) {
        this.waardeDate = waardeDate;
    }


    
    @Column(name="Waarde_string", length=100)
    public String getWaardeString() {
        return this.waardeString;
    }
    
    public void setWaardeString(String waardeString) {
        this.waardeString = waardeString;
    }





}


