package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * Eigenschap generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="Eigenschap")
@Table(name="Eigenschap"
)
public class Eigenschap  implements java.io.Serializable {


     private Integer eigenschapId;
     private String code;
     private String omschrijving;
     private boolean actief;
     private Set<GebruikerEigenschap> gebruikerEigenschappen = new HashSet<GebruikerEigenschap>(0);

    public Eigenschap() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Eigenschap_ID", unique=true, nullable=false)
    public Integer getEigenschapId() {
        return this.eigenschapId;
    }
    
    public void setEigenschapId(Integer eigenschapId) {
        this.eigenschapId = eigenschapId;
    }


    
    @Column(name="Code", nullable=false, length=5)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }


    
    @Column(name="Omschrijving", length=100)
    public String getOmschrijving() {
        return this.omschrijving;
    }
    
    public void setOmschrijving(String omschrijving) {
        this.omschrijving = omschrijving;
    }


    
    @Column(name="Actief", nullable=false)
    public boolean isActief() {
        return this.actief;
    }
    
    public void setActief(boolean actief) {
        this.actief = actief;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="eigenschap")
    public Set<GebruikerEigenschap> getGebruikerEigenschappen() {
        return this.gebruikerEigenschappen;
    }
    
    public void setGebruikerEigenschappen(Set<GebruikerEigenschap> gebruikerEigenschappen) {
        this.gebruikerEigenschappen = gebruikerEigenschappen;
    }





}


