package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * ExactOnlineAccess generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="ExactOnlineAccess")
@Table(name="ExactOnlineAccess"
)
public class ExactOnlineAccess  implements java.io.Serializable {


     private Integer exactOnlineAccessId;
     private String accessToken;
     private String refreshToken;
     private Date datumAccessTokenExpire;
     private Date datumAangemaakt;
     private Date datumGewijzigd;

    public ExactOnlineAccess() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ExactOnlineAccess_ID", unique=true, nullable=false)
    public Integer getExactOnlineAccessId() {
        return this.exactOnlineAccessId;
    }
    
    public void setExactOnlineAccessId(Integer exactOnlineAccessId) {
        this.exactOnlineAccessId = exactOnlineAccessId;
    }


    
    @Column(name="AccessToken", length=1024)
    public String getAccessToken() {
        return this.accessToken;
    }
    
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }


    
    @Column(name="RefreshToken", length=1024)
    public String getRefreshToken() {
        return this.refreshToken;
    }
    
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DatumAccessTokenExpire", length=19)
    public Date getDatumAccessTokenExpire() {
        return this.datumAccessTokenExpire;
    }
    
    public void setDatumAccessTokenExpire(Date datumAccessTokenExpire) {
        this.datumAccessTokenExpire = datumAccessTokenExpire;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DatumAangemaakt", length=19)
    public Date getDatumAangemaakt() {
        return this.datumAangemaakt;
    }
    
    public void setDatumAangemaakt(Date datumAangemaakt) {
        this.datumAangemaakt = datumAangemaakt;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DatumGewijzigd", length=19)
    public Date getDatumGewijzigd() {
        return this.datumGewijzigd;
    }
    
    public void setDatumGewijzigd(Date datumGewijzigd) {
        this.datumGewijzigd = datumGewijzigd;
    }





}


