package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * FactuurConfig generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="FactuurConfig")
@Table(name="FactuurConfig"
)
public class FactuurConfig  implements java.io.Serializable {


     private Integer factuurConfigId;
     private FacturatieFrequentie facturatieFrequentie;
     private Product product;
     private Date laatsteFactuurDatum;
     private String exactOnlineGlAccountCode;
     private String exactOnlineJournal;

    public FactuurConfig() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="FactuurConfig_ID", unique=true, nullable=false)
    public Integer getFactuurConfigId() {
        return this.factuurConfigId;
    }
    
    public void setFactuurConfigId(Integer factuurConfigId) {
        this.factuurConfigId = factuurConfigId;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FacturatieFrequentie", nullable=false)
    public FacturatieFrequentie getFacturatieFrequentie() {
        return this.facturatieFrequentie;
    }
    
    public void setFacturatieFrequentie(FacturatieFrequentie facturatieFrequentie) {
        this.facturatieFrequentie = facturatieFrequentie;
    }



    @Transient
    public String getFacturatieFrequentieCode() {
        return this.facturatieFrequentie == null ? null : this.facturatieFrequentie.getCode();
    }

    public void setFacturatieFrequentieCode(String code) {
        if (code == null) {
            this.facturatieFrequentie = null;
        } else {
            FacturatieFrequentie obj = new FacturatieFrequentie();
            obj.setCode(code);
            this.facturatieFrequentie = obj;
        }
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ProductCode", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }



    @Transient
    public String getProductCode() {
        return this.product == null ? null : this.product.getCode();
    }

    public void setProductCode(String code) {
        if (code == null) {
            this.product = null;
        } else {
            Product obj = new Product();
            obj.setCode(code);
            this.product = obj;
        }
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.DATE)
    @Column(name="LaatsteFactuurDatum", length=10)
    public Date getLaatsteFactuurDatum() {
        return this.laatsteFactuurDatum;
    }
    
    public void setLaatsteFactuurDatum(Date laatsteFactuurDatum) {
        this.laatsteFactuurDatum = laatsteFactuurDatum;
    }


    
    @Column(name="ExactOnlineGlAccountCode", length=10)
    public String getExactOnlineGlAccountCode() {
        return this.exactOnlineGlAccountCode;
    }
    
    public void setExactOnlineGlAccountCode(String exactOnlineGlAccountCode) {
        this.exactOnlineGlAccountCode = exactOnlineGlAccountCode;
    }


    
    @Column(name="ExactOnlineJournal", length=10)
    public String getExactOnlineJournal() {
        return this.exactOnlineJournal;
    }
    
    public void setExactOnlineJournal(String exactOnlineJournal) {
        this.exactOnlineJournal = exactOnlineJournal;
    }





}


