package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * Factuur generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="Factuur")
@Table(name="Factuur"
)
public class Factuur  implements java.io.Serializable {


     private Integer factuurId;
     private Bedrijf bedrijf;
     private Date datumFactuur;
     private BigDecimal bedrag;
     private Date datumAangemaakt;
     private Date datumVerwerktExactOnline;
     private String referentie;
     private String salesEntryGuid;
     private String fileNaam;
     private Set<FactuurRegel> factuurRegels = new HashSet<FactuurRegel>(0);

    public Factuur() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Factuur_ID", unique=true, nullable=false)
    public Integer getFactuurId() {
        return this.factuurId;
    }
    
    public void setFactuurId(Integer factuurId) {
        this.factuurId = factuurId;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Bedrijf_ID")
    public Bedrijf getBedrijf() {
        return this.bedrijf;
    }
    
    public void setBedrijf(Bedrijf bedrijf) {
        this.bedrijf = bedrijf;
    }



    @Transient
    public Integer getBedrijfBedrijfId() {
        return this.bedrijf == null ? null : this.bedrijf.getBedrijfId();
    }

    public void setBedrijfBedrijfId(Integer bedrijfId) {
        if (bedrijfId == null) {
            this.bedrijf = null;
        } else {
            Bedrijf obj = new Bedrijf();
            obj.setBedrijfId(bedrijfId);
            this.bedrijf = obj;
        }
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DatumFactuur", length=19)
    public Date getDatumFactuur() {
        return this.datumFactuur;
    }
    
    public void setDatumFactuur(Date datumFactuur) {
        this.datumFactuur = datumFactuur;
    }


    
    @Column(name="Bedrag", precision=10)
    public BigDecimal getBedrag() {
        return this.bedrag;
    }
    
    public void setBedrag(BigDecimal bedrag) {
        this.bedrag = bedrag;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DatumAangemaakt", length=19)
    public Date getDatumAangemaakt() {
        return this.datumAangemaakt;
    }
    
    public void setDatumAangemaakt(Date datumAangemaakt) {
        this.datumAangemaakt = datumAangemaakt;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DatumVerwerktExactOnline", length=19)
    public Date getDatumVerwerktExactOnline() {
        return this.datumVerwerktExactOnline;
    }
    
    public void setDatumVerwerktExactOnline(Date datumVerwerktExactOnline) {
        this.datumVerwerktExactOnline = datumVerwerktExactOnline;
    }


    
    @Column(name="Referentie", length=20)
    public String getReferentie() {
        return this.referentie;
    }
    
    public void setReferentie(String referentie) {
        this.referentie = referentie;
    }


    
    @Column(name="SalesEntryGuid", length=36)
    public String getSalesEntryGuid() {
        return this.salesEntryGuid;
    }
    
    public void setSalesEntryGuid(String salesEntryGuid) {
        this.salesEntryGuid = salesEntryGuid;
    }


    
    @Column(name="FileNaam", length=50)
    public String getFileNaam() {
        return this.fileNaam;
    }
    
    public void setFileNaam(String fileNaam) {
        this.fileNaam = fileNaam;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="factuur")
    public Set<FactuurRegel> getFactuurRegels() {
        return this.factuurRegels;
    }
    
    public void setFactuurRegels(Set<FactuurRegel> factuurRegels) {
        this.factuurRegels = factuurRegels;
    }





}


