package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * Hours generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="Hours")
@Table(name="Hours"
)
public class Hours  implements java.io.Serializable {


     private short hourNr;

    public Hours() {
    }

   
     @Id 

    
    @Column(name="HourNr", unique=true, nullable=false)
    public short getHourNr() {
        return this.hourNr;
    }
    
    public void setHourNr(short hourNr) {
        this.hourNr = hourNr;
    }





}


