package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * InternalProcessStatus generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="InternalProcessStatus")
@Table(name="InternalProcessStatus"
)
public class InternalProcessStatus  implements java.io.Serializable {


     private String code;
     private InternalProcessType internalProcessType;
     private String omschrijving;
     private boolean actief;
     private Set<InternalProcess> internalProcesses = new HashSet<InternalProcess>(0);

    public InternalProcessStatus() {
    }

   
     @Id 

    
    @Column(name="Code", unique=true, nullable=false, length=3)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="InternalProcessType", nullable=false)
    public InternalProcessType getInternalProcessType() {
        return this.internalProcessType;
    }
    
    public void setInternalProcessType(InternalProcessType internalProcessType) {
        this.internalProcessType = internalProcessType;
    }



    @Transient
    public String getInternalProcessTypeCode() {
        return this.internalProcessType == null ? null : this.internalProcessType.getCode();
    }

    public void setInternalProcessTypeCode(String code) {
        if (code == null) {
            this.internalProcessType = null;
        } else {
            InternalProcessType obj = new InternalProcessType();
            obj.setCode(code);
            this.internalProcessType = obj;
        }
    }


    
    @Column(name="Omschrijving", nullable=false, length=100)
    public String getOmschrijving() {
        return this.omschrijving;
    }
    
    public void setOmschrijving(String omschrijving) {
        this.omschrijving = omschrijving;
    }


    
    @Column(name="Actief", nullable=false)
    public boolean isActief() {
        return this.actief;
    }
    
    public void setActief(boolean actief) {
        this.actief = actief;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="internalProcessStatus")
    public Set<InternalProcess> getInternalProcesses() {
        return this.internalProcesses;
    }
    
    public void setInternalProcesses(Set<InternalProcess> internalProcesses) {
        this.internalProcesses = internalProcesses;
    }





}


