package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * KortingsCode generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="KortingsCode")
@Table(name="KortingsCode"
)
public class KortingsCode  implements java.io.Serializable {


     private String code;
     private boolean actief;
     private Date geldigVan;
     private Date geldigTot;
     private Set<Klant> klanten = new HashSet<Klant>(0);

    public KortingsCode() {
    }

   
     @Id 

    
    @Column(name="Code", unique=true, nullable=false, length=25)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }


    
    @Column(name="Actief", nullable=false)
    public boolean isActief() {
        return this.actief;
    }
    
    public void setActief(boolean actief) {
        this.actief = actief;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="GeldigVan", nullable=false, length=19)
    public Date getGeldigVan() {
        return this.geldigVan;
    }
    
    public void setGeldigVan(Date geldigVan) {
        this.geldigVan = geldigVan;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="GeldigTot", nullable=false, length=19)
    public Date getGeldigTot() {
        return this.geldigTot;
    }
    
    public void setGeldigTot(Date geldigTot) {
        this.geldigTot = geldigTot;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="kortingsCode")
    public Set<Klant> getKlanten() {
        return this.klanten;
    }
    
    public void setKlanten(Set<Klant> klanten) {
        this.klanten = klanten;
    }





}


