package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * Melding generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="Melding")
@Table(name="Melding"
)
public class Melding  implements java.io.Serializable {


     private Integer meldingId;
     private MeldingBatch meldingBatch;
     private MeldingStatus meldingStatus;
     private Notitie notitieGebruiker;
     private Notitie notitieAdmin;
     private Document document;
     private Bedrijf bedrijfByMeldingOverBedrijfId;
     private Bedrijf bedrijfByMeldingDoorBedrijfId;
     private Gebruiker gebruikerByVerwijderdDoorGebruikerId;
     private Gebruiker gebruikerByGeaccordeerdDoorGebruikerId;
     private BriefBatch briefBatch;
     private RedenVerwijderenMelding redenVerwijderenMelding;
     private Gebruiker gebruikerByMeldingDoorGebruikerId;
     private Gebruiker gebruikerByLaatsteMutatieDoorGebruikerId;
     private BriefStatus briefStatus;
     private Gebruiker gebruikerByGeparkeerdDoorGebruikerId;
     private String referentieNummer;
     private Date datumIngediend;
     private BigDecimal bedrag;
     private Date datumVerloopFactuur;
     private Date datumGeaccordeerd;
     private Date datumVerwijderd;
     private String referentieNummerIntern;
     private boolean doorBedrijfWeergeven;
     private boolean bedragWeergeven;
     private Date datumLaatsteMutatie;
     private BigDecimal oorspronkelijkBedrag;
     private Date datumGeparkeerd;
     private String telefoonNummerDebiteur;
     private String emailAdresDebiteur;
     private Set<InternalProcess> internalProcesses = new HashSet<InternalProcess>(0);
     private Set<Support> supports = new HashSet<Support>(0);
     private Set<Alert> alerts = new HashSet<Alert>(0);

    public Melding() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Melding_ID", unique=true, nullable=false)
    public Integer getMeldingId() {
        return this.meldingId;
    }
    
    public void setMeldingId(Integer meldingId) {
        this.meldingId = meldingId;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MeldingBatch_ID")
    public MeldingBatch getMeldingBatch() {
        return this.meldingBatch;
    }
    
    public void setMeldingBatch(MeldingBatch meldingBatch) {
        this.meldingBatch = meldingBatch;
    }



    @Transient
    public Integer getMeldingBatchMeldingBatchId() {
        return this.meldingBatch == null ? null : this.meldingBatch.getMeldingBatchId();
    }

    public void setMeldingBatchMeldingBatchId(Integer meldingBatchId) {
        if (meldingBatchId == null) {
            this.meldingBatch = null;
        } else {
            MeldingBatch obj = new MeldingBatch();
            obj.setMeldingBatchId(meldingBatchId);
            this.meldingBatch = obj;
        }
    }

@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MeldingStatus")
    public MeldingStatus getMeldingStatus() {
        return this.meldingStatus;
    }
    
    public void setMeldingStatus(MeldingStatus meldingStatus) {
        this.meldingStatus = meldingStatus;
    }



    @Transient
    public String getMeldingStatusCode() {
        return this.meldingStatus == null ? null : this.meldingStatus.getCode();
    }

    public void setMeldingStatusCode(String code) {
        if (code == null) {
            this.meldingStatus = null;
        } else {
            MeldingStatus obj = new MeldingStatus();
            obj.setCode(code);
            this.meldingStatus = obj;
        }
    }
    

@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NotitieGebruiker_ID")
    public Notitie getNotitieGebruiker() {
        return this.notitieGebruiker;
    }
    
    public void setNotitieGebruiker(Notitie notitieGebruiker) {
        this.notitieGebruiker = notitieGebruiker;
    }



    @Transient
    public Integer getNotitieGebruikerId() {
        return this.notitieGebruiker == null ? null : this.notitieGebruiker.getNotitieId();
    }

    public void setNotitieGebruikerId(Integer notitieGebruikerId) {
        if (notitieGebruikerId == null) {
            this.notitieGebruiker = null;
        } else {
            Notitie obj = new Notitie();
            obj.setNotitieId(notitieGebruikerId);
            this.notitieGebruiker = obj;
        }
    }

@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NotitieAdmin_ID")
    public Notitie getNotitieAdmin() {
        return this.notitieAdmin;
    }
    
    public void setNotitieAdmin(Notitie notitieAdmin) {
        this.notitieAdmin = notitieAdmin;
    }



    @Transient
    public Integer getNotitieAdminId() {
        return this.notitieAdmin == null ? null : this.notitieAdmin.getNotitieId();
    }

    public void setNotitieAdminId(Integer notitieAdminId) {
        if (notitieAdminId == null) {
            this.notitieAdmin = null;
        } else {
            Notitie obj = new Notitie();
            obj.setNotitieId(notitieAdminId);
            this.notitieAdmin = obj;
        }
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Document_ID")
    public Document getDocument() {
        return this.document;
    }
    
    public void setDocument(Document document) {
        this.document = document;
    }



    @Transient
    public Integer getDocumentDocumentId() {
        return this.document == null ? null : this.document.getDocumentId();
    }

    public void setDocumentDocumentId(Integer documentId) {
        if (documentId == null) {
            this.document = null;
        } else {
            Document obj = new Document();
            obj.setDocumentId(documentId);
            this.document = obj;
        }
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MeldingOverBedrijf_ID", nullable=false)
    public Bedrijf getBedrijfByMeldingOverBedrijfId() {
        return this.bedrijfByMeldingOverBedrijfId;
    }
    
    public void setBedrijfByMeldingOverBedrijfId(Bedrijf bedrijfByMeldingOverBedrijfId) {
        this.bedrijfByMeldingOverBedrijfId = bedrijfByMeldingOverBedrijfId;
    }



    @Transient
    public Integer getBedrijfByMeldingOverBedrijfIdBedrijfId() {
        return this.bedrijfByMeldingOverBedrijfId == null ? null : this.bedrijfByMeldingOverBedrijfId.getBedrijfId();
    }

    public void setBedrijfByMeldingOverBedrijfIdBedrijfId(Integer bedrijfId) {
        if (bedrijfId == null) {
            this.bedrijfByMeldingOverBedrijfId = null;
        } else {
            Bedrijf obj = new Bedrijf();
            obj.setBedrijfId(bedrijfId);
            this.bedrijfByMeldingOverBedrijfId = obj;
        }
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MeldingDoorBedrijf_ID", nullable=false)
    public Bedrijf getBedrijfByMeldingDoorBedrijfId() {
        return this.bedrijfByMeldingDoorBedrijfId;
    }
    
    public void setBedrijfByMeldingDoorBedrijfId(Bedrijf bedrijfByMeldingDoorBedrijfId) {
        this.bedrijfByMeldingDoorBedrijfId = bedrijfByMeldingDoorBedrijfId;
    }



    @Transient
    public Integer getBedrijfByMeldingDoorBedrijfIdBedrijfId() {
        return this.bedrijfByMeldingDoorBedrijfId == null ? null : this.bedrijfByMeldingDoorBedrijfId.getBedrijfId();
    }

    public void setBedrijfByMeldingDoorBedrijfIdBedrijfId(Integer bedrijfId) {
        if (bedrijfId == null) {
            this.bedrijfByMeldingDoorBedrijfId = null;
        } else {
            Bedrijf obj = new Bedrijf();
            obj.setBedrijfId(bedrijfId);
            this.bedrijfByMeldingDoorBedrijfId = obj;
        }
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VerwijderdDoorGebruiker_ID")
    public Gebruiker getGebruikerByVerwijderdDoorGebruikerId() {
        return this.gebruikerByVerwijderdDoorGebruikerId;
    }
    
    public void setGebruikerByVerwijderdDoorGebruikerId(Gebruiker gebruikerByVerwijderdDoorGebruikerId) {
        this.gebruikerByVerwijderdDoorGebruikerId = gebruikerByVerwijderdDoorGebruikerId;
    }



    @Transient
    public Integer getGebruikerByVerwijderdDoorGebruikerIdGebruikerId() {
        return this.gebruikerByVerwijderdDoorGebruikerId == null ? null : this.gebruikerByVerwijderdDoorGebruikerId.getGebruikerId();
    }

    public void setGebruikerByVerwijderdDoorGebruikerIdGebruikerId(int gebruikerId) {
        Gebruiker obj = new Gebruiker();
        obj.setGebruikerId(gebruikerId);
        this.gebruikerByVerwijderdDoorGebruikerId = obj;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GeaccordeerdDoorGebruiker_ID")
    public Gebruiker getGebruikerByGeaccordeerdDoorGebruikerId() {
        return this.gebruikerByGeaccordeerdDoorGebruikerId;
    }
    
    public void setGebruikerByGeaccordeerdDoorGebruikerId(Gebruiker gebruikerByGeaccordeerdDoorGebruikerId) {
        this.gebruikerByGeaccordeerdDoorGebruikerId = gebruikerByGeaccordeerdDoorGebruikerId;
    }



    @Transient
    public Integer getGebruikerByGeaccordeerdDoorGebruikerIdGebruikerId() {
        return this.gebruikerByGeaccordeerdDoorGebruikerId == null ? null : this.gebruikerByGeaccordeerdDoorGebruikerId.getGebruikerId();
    }

    public void setGebruikerByGeaccordeerdDoorGebruikerIdGebruikerId(int gebruikerId) {
        Gebruiker obj = new Gebruiker();
        obj.setGebruikerId(gebruikerId);
        this.gebruikerByGeaccordeerdDoorGebruikerId = obj;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BriefBatch_ID")
    public BriefBatch getBriefBatch() {
        return this.briefBatch;
    }
    
    public void setBriefBatch(BriefBatch briefBatch) {
        this.briefBatch = briefBatch;
    }



    @Transient
    public Integer getBriefBatchBriefBatchId() {
        return this.briefBatch == null ? null : this.briefBatch.getBriefBatchId();
    }

    public void setBriefBatchBriefBatchId(Integer briefBatchId) {
        if (briefBatchId == null) {
            this.briefBatch = null;
        } else {
            BriefBatch obj = new BriefBatch();
            obj.setBriefBatchId(briefBatchId);
            this.briefBatch = obj;
        }
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RedenVerwijderenCode")
    public RedenVerwijderenMelding getRedenVerwijderenMelding() {
        return this.redenVerwijderenMelding;
    }
    
    public void setRedenVerwijderenMelding(RedenVerwijderenMelding redenVerwijderenMelding) {
        this.redenVerwijderenMelding = redenVerwijderenMelding;
    }



    @Transient
    public String getRedenVerwijderenMeldingCode() {
        return this.redenVerwijderenMelding == null ? null : this.redenVerwijderenMelding.getCode();
    }

    public void setRedenVerwijderenMeldingCode(String code) {
        if (code == null) {
            this.redenVerwijderenMelding = null;
        } else {
            RedenVerwijderenMelding obj = new RedenVerwijderenMelding();
            obj.setCode(code);
            this.redenVerwijderenMelding = obj;
        }
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MeldingDoorGebruiker_ID")
    public Gebruiker getGebruikerByMeldingDoorGebruikerId() {
        return this.gebruikerByMeldingDoorGebruikerId;
    }
    
    public void setGebruikerByMeldingDoorGebruikerId(Gebruiker gebruikerByMeldingDoorGebruikerId) {
        this.gebruikerByMeldingDoorGebruikerId = gebruikerByMeldingDoorGebruikerId;
    }



    @Transient
    public Integer getGebruikerByMeldingDoorGebruikerIdGebruikerId() {
        return this.gebruikerByMeldingDoorGebruikerId == null ? null : this.gebruikerByMeldingDoorGebruikerId.getGebruikerId();
    }

    public void setGebruikerByMeldingDoorGebruikerIdGebruikerId(int gebruikerId) {
        Gebruiker obj = new Gebruiker();
        obj.setGebruikerId(gebruikerId);
        this.gebruikerByMeldingDoorGebruikerId = obj;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LaatsteMutatieDoorGebruiker_ID")
    public Gebruiker getGebruikerByLaatsteMutatieDoorGebruikerId() {
        return this.gebruikerByLaatsteMutatieDoorGebruikerId;
    }
    
    public void setGebruikerByLaatsteMutatieDoorGebruikerId(Gebruiker gebruikerByLaatsteMutatieDoorGebruikerId) {
        this.gebruikerByLaatsteMutatieDoorGebruikerId = gebruikerByLaatsteMutatieDoorGebruikerId;
    }



    @Transient
    public Integer getGebruikerByLaatsteMutatieDoorGebruikerIdGebruikerId() {
        return this.gebruikerByLaatsteMutatieDoorGebruikerId == null ? null : this.gebruikerByLaatsteMutatieDoorGebruikerId.getGebruikerId();
    }

    public void setGebruikerByLaatsteMutatieDoorGebruikerIdGebruikerId(int gebruikerId) {
        Gebruiker obj = new Gebruiker();
        obj.setGebruikerId(gebruikerId);
        this.gebruikerByLaatsteMutatieDoorGebruikerId = obj;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BriefStatus", nullable=false)
    public BriefStatus getBriefStatus() {
        return this.briefStatus;
    }
    
    public void setBriefStatus(BriefStatus briefStatus) {
        this.briefStatus = briefStatus;
    }



    @Transient
    public String getBriefStatusCode() {
        return this.briefStatus == null ? null : this.briefStatus.getCode();
    }

    public void setBriefStatusCode(String code) {
        if (code == null) {
            this.briefStatus = null;
        } else {
            BriefStatus obj = new BriefStatus();
            obj.setCode(code);
            this.briefStatus = obj;
        }
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GeparkeerdDoorGebruiker_ID")
    public Gebruiker getGebruikerByGeparkeerdDoorGebruikerId() {
        return this.gebruikerByGeparkeerdDoorGebruikerId;
    }
    
    public void setGebruikerByGeparkeerdDoorGebruikerId(Gebruiker gebruikerByGeparkeerdDoorGebruikerId) {
        this.gebruikerByGeparkeerdDoorGebruikerId = gebruikerByGeparkeerdDoorGebruikerId;
    }



    @Transient
    public Integer getGebruikerByGeparkeerdDoorGebruikerIdGebruikerId() {
        return this.gebruikerByGeparkeerdDoorGebruikerId == null ? null : this.gebruikerByGeparkeerdDoorGebruikerId.getGebruikerId();
    }

    public void setGebruikerByGeparkeerdDoorGebruikerIdGebruikerId(int gebruikerId) {
        Gebruiker obj = new Gebruiker();
        obj.setGebruikerId(gebruikerId);
        this.gebruikerByGeparkeerdDoorGebruikerId = obj;
    }


    
    @Column(name="ReferentieNummer", length=50)
    public String getReferentieNummer() {
        return this.referentieNummer;
    }
    
    public void setReferentieNummer(String referentieNummer) {
        this.referentieNummer = referentieNummer;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DatumIngediend", nullable=false, length=19)
    public Date getDatumIngediend() {
        return this.datumIngediend;
    }
    
    public void setDatumIngediend(Date datumIngediend) {
        this.datumIngediend = datumIngediend;
    }


    
    @Column(name="Bedrag", precision=10)
    public BigDecimal getBedrag() {
        return this.bedrag;
    }
    
    public void setBedrag(BigDecimal bedrag) {
        this.bedrag = bedrag;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DatumVerloopFactuur", length=19)
    public Date getDatumVerloopFactuur() {
        return this.datumVerloopFactuur;
    }
    
    public void setDatumVerloopFactuur(Date datumVerloopFactuur) {
        this.datumVerloopFactuur = datumVerloopFactuur;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DatumGeaccordeerd", length=19)
    public Date getDatumGeaccordeerd() {
        return this.datumGeaccordeerd;
    }
    
    public void setDatumGeaccordeerd(Date datumGeaccordeerd) {
        this.datumGeaccordeerd = datumGeaccordeerd;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DatumVerwijderd", length=19)
    public Date getDatumVerwijderd() {
        return this.datumVerwijderd;
    }
    
    public void setDatumVerwijderd(Date datumVerwijderd) {
        this.datumVerwijderd = datumVerwijderd;
    }


    
    @Column(name="ReferentieNummerIntern", length=50)
    public String getReferentieNummerIntern() {
        return this.referentieNummerIntern;
    }
    
    public void setReferentieNummerIntern(String referentieNummerIntern) {
        this.referentieNummerIntern = referentieNummerIntern;
    }


    
    @Column(name="DoorBedrijfWeergeven", nullable=false)
    public boolean isDoorBedrijfWeergeven() {
        return this.doorBedrijfWeergeven;
    }
    
    public void setDoorBedrijfWeergeven(boolean doorBedrijfWeergeven) {
        this.doorBedrijfWeergeven = doorBedrijfWeergeven;
    }


    
    @Column(name="BedragWeergeven", nullable=false)
    public boolean isBedragWeergeven() {
        return this.bedragWeergeven;
    }
    
    public void setBedragWeergeven(boolean bedragWeergeven) {
        this.bedragWeergeven = bedragWeergeven;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DatumLaatsteMutatie", length=19)
    public Date getDatumLaatsteMutatie() {
        return this.datumLaatsteMutatie;
    }
    
    public void setDatumLaatsteMutatie(Date datumLaatsteMutatie) {
        this.datumLaatsteMutatie = datumLaatsteMutatie;
    }


    
    @Column(name="OorspronkelijkBedrag", precision=10)
    public BigDecimal getOorspronkelijkBedrag() {
        return this.oorspronkelijkBedrag;
    }
    
    public void setOorspronkelijkBedrag(BigDecimal oorspronkelijkBedrag) {
        this.oorspronkelijkBedrag = oorspronkelijkBedrag;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DatumGeparkeerd", length=19)
    public Date getDatumGeparkeerd() {
        return this.datumGeparkeerd;
    }
    
    public void setDatumGeparkeerd(Date datumGeparkeerd) {
        this.datumGeparkeerd = datumGeparkeerd;
    } 


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="melding")
    public Set<InternalProcess> getInternalProcesses() {
        return this.internalProcesses;
    }
    
    public void setInternalProcesses(Set<InternalProcess> internalProcesses) {
        this.internalProcesses = internalProcesses;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="melding")
    public Set<Support> getSupports() {
        return this.supports;
    }
    
    public void setSupports(Set<Support> supports) {
        this.supports = supports;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="melding")
    public Set<Alert> getAlerts() {
        return this.alerts;
    }
    
    public void setAlerts(Set<Alert> alerts) {
        this.alerts = alerts;
    }


    @Column(name="TelefoonNummerDebiteur", length=40)
	public String getTelefoonNummerDebiteur() {
		return telefoonNummerDebiteur;
	}


	public void setTelefoonNummerDebiteur(String telefoonNummerDebiteur) {
		this.telefoonNummerDebiteur = telefoonNummerDebiteur;
	}


    @Column(name="EmailAdresDebiteur", length=50)
	public String getEmailAdresDebiteur() {
		return emailAdresDebiteur;
	}


	public void setEmailAdresDebiteur(String emailAdresDebiteur) {
		this.emailAdresDebiteur = emailAdresDebiteur;
	}





}


