package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * Persoon generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="Persoon")
@Table(name="Persoon"
)
public class Persoon  implements java.io.Serializable {


     private Integer persoonId;
     private String naam;
     private String initialen;
     private String prefix;
     private String voornaam;
     private Date datumGeboren;
     private Set<Bedrijf> bedrijven = new HashSet<Bedrijf>(0);

    public Persoon() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Persoon_ID", unique=true, nullable=false)
    public Integer getPersoonId() {
        return this.persoonId;
    }
    
    public void setPersoonId(Integer persoonId) {
        this.persoonId = persoonId;
    }


    
    @Column(name="Naam", nullable=false, length=35)
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }


    
    @Column(name="Initialen", nullable=false, length=7)
    public String getInitialen() {
        return this.initialen;
    }
    
    public void setInitialen(String initialen) {
        this.initialen = initialen;
    }


    
    @Column(name="Prefix", length=10)
    public String getPrefix() {
        return this.prefix;
    }
    
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }


    
    @Column(name="Voornaam", length=35)
    public String getVoornaam() {
        return this.voornaam;
    }
    
    public void setVoornaam(String voornaam) {
        this.voornaam = voornaam;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.DATE)
    @Column(name="DatumGeboren", length=10)
    public Date getDatumGeboren() {
        return this.datumGeboren;
    }
    
    public void setDatumGeboren(Date datumGeboren) {
        this.datumGeboren = datumGeboren;
    }


@XmlTransient
@JsonIgnore
@ManyToMany(fetch=FetchType.LAZY, mappedBy="personen")
    public Set<Bedrijf> getBedrijven() {
        return this.bedrijven;
    }
    
    public void setBedrijven(Set<Bedrijf> bedrijven) {
        this.bedrijven = bedrijven;
    }





}


