package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * Rechtsvorm generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="Rechtsvorm")
@Table(name="Rechtsvorm"
)
public class Rechtsvorm  implements java.io.Serializable {


     private Integer rechtsvormId;
     private String code;
     private String omschrijving;

    public Rechtsvorm() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Rechtsvorm_ID", unique=true, nullable=false)
    public Integer getRechtsvormId() {
        return this.rechtsvormId;
    }
    
    public void setRechtsvormId(Integer rechtsvormId) {
        this.rechtsvormId = rechtsvormId;
    }


    
    @Column(name="Code", length=10)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }


    
    @Column(name="Omschrijving")
    public String getOmschrijving() {
        return this.omschrijving;
    }
    
    public void setOmschrijving(String omschrijving) {
        this.omschrijving = omschrijving;
    }





}


