package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * RemovedBedrijf generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="RemovedBedrijf")
@Table(name="RemovedBedrijf"
)
public class RemovedBedrijf  implements java.io.Serializable {


     private String removedBedrijfId;
     private Integer doorBedrijfId;
     private int bedrijfId;
     private String bedrijfsNaam;
     private String kvkNummer;
     private String subDossier;
     private Integer monitoringId;
     private Integer meldingId;
     private Date datumStart;
     private Date datumEinde;
     private Integer gebruikerAangemaaktId;
     private Integer gebruikerVerwijderdId;
     private String referentieNummer;
     private String referentieNummerIntern;
     private String status;
     private String redenVerwijderenCode;

    public RemovedBedrijf() {
    }

   
     @Id 

    
    @Column(name="removedBedrijf_id", length=36)
    public String getRemovedBedrijfId() {
        return this.removedBedrijfId;
    }
    
    public void setRemovedBedrijfId(String removedBedrijfId) {
        this.removedBedrijfId = removedBedrijfId;
    }


    
    @Column(name="doorBedrijf_id")
    public Integer getDoorBedrijfId() {
        return this.doorBedrijfId;
    }
    
    public void setDoorBedrijfId(Integer doorBedrijfId) {
        this.doorBedrijfId = doorBedrijfId;
    }


    
    @Column(name="bedrijf_id", nullable=false)
    public int getBedrijfId() {
        return this.bedrijfId;
    }
    
    public void setBedrijfId(int bedrijfId) {
        this.bedrijfId = bedrijfId;
    }


    
    @Column(name="bedrijfsNaam")
    public String getBedrijfsNaam() {
        return this.bedrijfsNaam;
    }
    
    public void setBedrijfsNaam(String bedrijfsNaam) {
        this.bedrijfsNaam = bedrijfsNaam;
    }


    
    @Column(name="kvkNummer", nullable=false, length=20)
    public String getKvkNummer() {
        return this.kvkNummer;
    }
    
    public void setKvkNummer(String kvkNummer) {
        this.kvkNummer = kvkNummer;
    }


    
    @Column(name="subDossier", length=20)
    public String getSubDossier() {
        return this.subDossier;
    }
    
    public void setSubDossier(String subDossier) {
        this.subDossier = subDossier;
    }


    
    @Column(name="monitoring_id")
    public Integer getMonitoringId() {
        return this.monitoringId;
    }
    
    public void setMonitoringId(Integer monitoringId) {
        this.monitoringId = monitoringId;
    }


    
    @Column(name="melding_id")
    public Integer getMeldingId() {
        return this.meldingId;
    }
    
    public void setMeldingId(Integer meldingId) {
        this.meldingId = meldingId;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datumStart", length=19)
    public Date getDatumStart() {
        return this.datumStart;
    }
    
    public void setDatumStart(Date datumStart) {
        this.datumStart = datumStart;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datumEinde", length=19)
    public Date getDatumEinde() {
        return this.datumEinde;
    }
    
    public void setDatumEinde(Date datumEinde) {
        this.datumEinde = datumEinde;
    }


    
    @Column(name="gebruikerAangemaakt_id")
    public Integer getGebruikerAangemaaktId() {
        return this.gebruikerAangemaaktId;
    }
    
    public void setGebruikerAangemaaktId(Integer gebruikerAangemaaktId) {
        this.gebruikerAangemaaktId = gebruikerAangemaaktId;
    }


    
    @Column(name="gebruikerVerwijderd_id")
    public Integer getGebruikerVerwijderdId() {
        return this.gebruikerVerwijderdId;
    }
    
    public void setGebruikerVerwijderdId(Integer gebruikerVerwijderdId) {
        this.gebruikerVerwijderdId = gebruikerVerwijderdId;
    }


    
    @Column(name="referentieNummer", length=50)
    public String getReferentieNummer() {
        return this.referentieNummer;
    }
    
    public void setReferentieNummer(String referentieNummer) {
        this.referentieNummer = referentieNummer;
    }


    
    @Column(name="referentieNummerIntern", length=50)
    public String getReferentieNummerIntern() {
        return this.referentieNummerIntern;
    }
    
    public void setReferentieNummerIntern(String referentieNummerIntern) {
        this.referentieNummerIntern = referentieNummerIntern;
    }


    
    @Column(name="status", length=3)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }


    
    @Column(name="redenVerwijderenCode", length=3)
    public String getRedenVerwijderenCode() {
        return this.redenVerwijderenCode;
    }
    
    public void setRedenVerwijderenCode(String redenVerwijderenCode) {
        this.redenVerwijderenCode = redenVerwijderenCode;
    }





}


