package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * SearchResult generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="SearchResult")
@Table(name="SearchResult"
)
public class SearchResult  implements java.io.Serializable {


     private String searchResultId;
     private Bedrijf vanBedrijf;
     private Bedrijf doorBedrijf;
     private String datatype;
     private String bedrijfsNaam;
     private String kvkNummer;
     private String subDossier;
     private Integer monitoringId;
     private Integer meldingId;
     private Integer documentId;
     private Integer bedrijfId;
     private Date datumStart;
     private Date datumEinde;
     private Integer gebruikerAangemaaktId;
     private String referentieNummerIntern;
     private String status;

    public SearchResult() {
    }

   
     @Id 

    
    @Column(name="searchResult_ID", length=36)
    public String getSearchResultId() {
        return this.searchResultId;
    }
    
    public void setSearchResultId(String searchResultId) {
        this.searchResultId = searchResultId;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vanBedrijf_id")
    public Bedrijf getVanBedrijf() {
        return this.vanBedrijf;
    }
    
    public void setVanBedrijf(Bedrijf vanBedrijf) {
        this.vanBedrijf = vanBedrijf;
    }



    @Transient
    public Integer getVanBedrijfBedrijfId() {
        return this.vanBedrijf == null ? null : this.vanBedrijf.getBedrijfId();
    }

    public void setVanBedrijfBedrijfId(Integer bedrijfId) {
        if (bedrijfId == null) {
            this.vanBedrijf = null;
        } else {
            Bedrijf obj = new Bedrijf();
            obj.setBedrijfId(bedrijfId);
            this.vanBedrijf = obj;
        }
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="doorBedrijf_id")
    public Bedrijf getDoorBedrijf() {
        return this.doorBedrijf;
    }
    
    public void setDoorBedrijf(Bedrijf doorBedrijf) {
        this.doorBedrijf = doorBedrijf;
    }



    @Transient
    public Integer getDoorBedrijfBedrijfId() {
        return this.doorBedrijf == null ? null : this.doorBedrijf.getBedrijfId();
    }

    public void setDoorBedrijfBedrijfId(Integer bedrijfId) {
        if (bedrijfId == null) {
            this.doorBedrijf = null;
        } else {
            Bedrijf obj = new Bedrijf();
            obj.setBedrijfId(bedrijfId);
            this.doorBedrijf = obj;
        }
    }


    
    @Column(name="datatype", nullable=false, length=3)
    public String getDatatype() {
        return this.datatype;
    }
    
    public void setDatatype(String datatype) {
        this.datatype = datatype;
    }


    
    @Column(name="bedrijfsNaam")
    public String getBedrijfsNaam() {
        return this.bedrijfsNaam;
    }
    
    public void setBedrijfsNaam(String bedrijfsNaam) {
        this.bedrijfsNaam = bedrijfsNaam;
    }


    
    @Column(name="kvkNummer", length=20)
    public String getKvkNummer() {
        return this.kvkNummer;
    }
    
    public void setKvkNummer(String kvkNummer) {
        this.kvkNummer = kvkNummer;
    }


    
    @Column(name="subDossier", length=20)
    public String getSubDossier() {
        return this.subDossier;
    }
    
    public void setSubDossier(String subDossier) {
        this.subDossier = subDossier;
    }


    
    @Column(name="monitoring_id")
    public Integer getMonitoringId() {
        return this.monitoringId;
    }
    
    public void setMonitoringId(Integer monitoringId) {
        this.monitoringId = monitoringId;
    }


    
    @Column(name="melding_id")
    public Integer getMeldingId() {
        return this.meldingId;
    }
    
    public void setMeldingId(Integer meldingId) {
        this.meldingId = meldingId;
    }


    
    @Column(name="document_id")
    public Integer getDocumentId() {
        return this.documentId;
    }
    
    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }


    
    @Column(name="bedrijf_id")
    public Integer getBedrijfId() {
        return this.bedrijfId;
    }
    
    public void setBedrijfId(Integer bedrijfId) {
        this.bedrijfId = bedrijfId;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datumStart", length=19)
    public Date getDatumStart() {
        return this.datumStart;
    }
    
    public void setDatumStart(Date datumStart) {
        this.datumStart = datumStart;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datumEinde", length=19)
    public Date getDatumEinde() {
        return this.datumEinde;
    }
    
    public void setDatumEinde(Date datumEinde) {
        this.datumEinde = datumEinde;
    }


    
    @Column(name="gebruikerAangemaakt_id")
    public Integer getGebruikerAangemaaktId() {
        return this.gebruikerAangemaaktId;
    }
    
    public void setGebruikerAangemaaktId(Integer gebruikerAangemaaktId) {
        this.gebruikerAangemaaktId = gebruikerAangemaaktId;
    }


    
    @Column(name="referentieNummerIntern", length=50)
    public String getReferentieNummerIntern() {
        return this.referentieNummerIntern;
    }
    
    public void setReferentieNummerIntern(String referentieNummerIntern) {
        this.referentieNummerIntern = referentieNummerIntern;
    }


    
    @Column(name="status", length=3)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }





}


