package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * Support generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="Support")
@Table(name="Support"
)
public class Support  implements java.io.Serializable {


     private Integer supportId;
     private SupportType supportType;
     private Support support;
     private SupportStatus supportStatus;
     private Melding melding;
     private Bedrijf bedrijf;
     private Gebruiker gebruikerByGeslotenDoorGebruikerId;
     private SupportReden supportReden;
     private Gebruiker gebruikerByGebruikerId;
     private String bericht;
     private String referentieNummer;
     private Date datumAangemaakt;
     private Date datumUpdate;
     private Boolean betwistBezwaar;
     private Set<Support> supports = new HashSet<Support>(0);
     private Set<SupportBestand> supportBestands = new HashSet<SupportBestand>(0);
     private Set<Alert> alerts = new HashSet<Alert>(0);

    public Support() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Support_ID", unique=true, nullable=false)
    public Integer getSupportId() {
        return this.supportId;
    }
    
    public void setSupportId(Integer supportId) {
        this.supportId = supportId;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SupportType", nullable=false)
    public SupportType getSupportType() {
        return this.supportType;
    }
    
    public void setSupportType(SupportType supportType) {
        this.supportType = supportType;
    }



    @Transient
    public String getSupportTypeCode() {
        return this.supportType == null ? null : this.supportType.getCode();
    }

    public void setSupportTypeCode(String code) {
        if (code == null) {
            this.supportType = null;
        } else {
            SupportType obj = new SupportType();
            obj.setCode(code);
            this.supportType = obj;
        }
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AntwoordOpSupport_ID")
    public Support getSupport() {
        return this.support;
    }
    
    public void setSupport(Support support) {
        this.support = support;
    }



    @Transient
    public Integer getSupportSupportId() {
        return this.support == null ? null : this.support.getSupportId();
    }

    public void setSupportSupportId(Integer supportId) {
        if (supportId == null) {
            this.support = null;
        } else {
            Support obj = new Support();
            obj.setSupportId(supportId);
            this.support = obj;
        }
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SupportStatus", nullable=false)
    public SupportStatus getSupportStatus() {
        return this.supportStatus;
    }
    
    public void setSupportStatus(SupportStatus supportStatus) {
        this.supportStatus = supportStatus;
    }



    @Transient
    public String getSupportStatusCode() {
        return this.supportStatus == null ? null : this.supportStatus.getCode();
    }

    public void setSupportStatusCode(String code) {
        if (code == null) {
            this.supportStatus = null;
        } else {
            SupportStatus obj = new SupportStatus();
            obj.setCode(code);
            this.supportStatus = obj;
        }
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Melding_ID")
    public Melding getMelding() {
        return this.melding;
    }
    
    public void setMelding(Melding melding) {
        this.melding = melding;
    }



    @Transient
    public Integer getMeldingMeldingId() {
        return this.melding == null ? null : this.melding.getMeldingId();
    }

    public void setMeldingMeldingId(Integer meldingId) {
        if (meldingId == null) {
            this.melding = null;
        } else {
            Melding obj = new Melding();
            obj.setMeldingId(meldingId);
            this.melding = obj;
        }
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BestemdVoorBedrijf_ID")
    public Bedrijf getBedrijf() {
        return this.bedrijf;
    }
    
    public void setBedrijf(Bedrijf bedrijf) {
        this.bedrijf = bedrijf;
    }



    @Transient
    public Integer getBedrijfBedrijfId() {
        return this.bedrijf == null ? null : this.bedrijf.getBedrijfId();
    }

    public void setBedrijfBedrijfId(Integer bedrijfId) {
        if (bedrijfId == null) {
            this.bedrijf = null;
        } else {
            Bedrijf obj = new Bedrijf();
            obj.setBedrijfId(bedrijfId);
            this.bedrijf = obj;
        }
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GeslotenDoorGebruiker_ID")
    public Gebruiker getGebruikerByGeslotenDoorGebruikerId() {
        return this.gebruikerByGeslotenDoorGebruikerId;
    }
    
    public void setGebruikerByGeslotenDoorGebruikerId(Gebruiker gebruikerByGeslotenDoorGebruikerId) {
        this.gebruikerByGeslotenDoorGebruikerId = gebruikerByGeslotenDoorGebruikerId;
    }



    @Transient
    public Integer getGebruikerByGeslotenDoorGebruikerIdGebruikerId() {
        return this.gebruikerByGeslotenDoorGebruikerId == null ? null : this.gebruikerByGeslotenDoorGebruikerId.getGebruikerId();
    }

    public void setGebruikerByGeslotenDoorGebruikerIdGebruikerId(int gebruikerId) {
        Gebruiker obj = new Gebruiker();
        obj.setGebruikerId(gebruikerId);
        this.gebruikerByGeslotenDoorGebruikerId = obj;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SupportReden")
    public SupportReden getSupportReden() {
        return this.supportReden;
    }
    
    public void setSupportReden(SupportReden supportReden) {
        this.supportReden = supportReden;
    }



    @Transient
    public String getSupportRedenCode() {
        return this.supportReden == null ? null : this.supportReden.getCode();
    }

    public void setSupportRedenCode(String code) {
        if (code == null) {
            this.supportReden = null;
        } else {
            SupportReden obj = new SupportReden();
            obj.setCode(code);
            this.supportReden = obj;
        }
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Gebruiker_ID", nullable=false)
    public Gebruiker getGebruikerByGebruikerId() {
        return this.gebruikerByGebruikerId;
    }
    
    public void setGebruikerByGebruikerId(Gebruiker gebruikerByGebruikerId) {
        this.gebruikerByGebruikerId = gebruikerByGebruikerId;
    }



    @Transient
    public Integer getGebruikerByGebruikerIdGebruikerId() {
        return this.gebruikerByGebruikerId == null ? null : this.gebruikerByGebruikerId.getGebruikerId();
    }

    public void setGebruikerByGebruikerIdGebruikerId(int gebruikerId) {
        Gebruiker obj = new Gebruiker();
        obj.setGebruikerId(gebruikerId);
        this.gebruikerByGebruikerId = obj;
    }


    
    @Column(name="Bericht", nullable=false, length=4096)
    public String getBericht() {
        return this.bericht;
    }
    
    public void setBericht(String bericht) {
        this.bericht = bericht;
    }


    
    @Column(name="ReferentieNummer", nullable=false, length=50)
    public String getReferentieNummer() {
        return this.referentieNummer;
    }
    
    public void setReferentieNummer(String referentieNummer) {
        this.referentieNummer = referentieNummer;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DatumAangemaakt", nullable=false, length=19)
    public Date getDatumAangemaakt() {
        return this.datumAangemaakt;
    }
    
    public void setDatumAangemaakt(Date datumAangemaakt) {
        this.datumAangemaakt = datumAangemaakt;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DatumUpdate", length=19)
    public Date getDatumUpdate() {
        return this.datumUpdate;
    }
    
    public void setDatumUpdate(Date datumUpdate) {
        this.datumUpdate = datumUpdate;
    }


    
    @Column(name="BetwistBezwaar")
    public Boolean getBetwistBezwaar() {
        return this.betwistBezwaar;
    }
    
    public void setBetwistBezwaar(Boolean betwistBezwaar) {
        this.betwistBezwaar = betwistBezwaar;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="support")
    public Set<Support> getSupports() {
        return this.supports;
    }
    
    public void setSupports(Set<Support> supports) {
        this.supports = supports;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="support")
    public Set<SupportBestand> getSupportBestands() {
        return this.supportBestands;
    }
    
    public void setSupportBestands(Set<SupportBestand> supportBestands) {
        this.supportBestands = supportBestands;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="support")
    public Set<Alert> getAlerts() {
        return this.alerts;
    }
    
    public void setAlerts(Set<Alert> alerts) {
        this.alerts = alerts;
    }





}


