package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * SupportReden generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="SupportReden")
@Table(name="SupportReden"
)
public class SupportReden  implements java.io.Serializable {


     private String code;
     private SupportType supportType;
     private String omschrijving;
     private boolean actief;
     private Set<Support> supports = new HashSet<Support>(0);

    public SupportReden() {
    }

   
     @Id 

    
    @Column(name="Code", unique=true, nullable=false, length=3)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SupportType", nullable=false)
    public SupportType getSupportType() {
        return this.supportType;
    }
    
    public void setSupportType(SupportType supportType) {
        this.supportType = supportType;
    }



    @Transient
    public String getSupportTypeCode() {
        return this.supportType == null ? null : this.supportType.getCode();
    }

    public void setSupportTypeCode(String code) {
        if (code == null) {
            this.supportType = null;
        } else {
            SupportType obj = new SupportType();
            obj.setCode(code);
            this.supportType = obj;
        }
    }


    
    @Column(name="Omschrijving", nullable=false, length=100)
    public String getOmschrijving() {
        return this.omschrijving;
    }
    
    public void setOmschrijving(String omschrijving) {
        this.omschrijving = omschrijving;
    }


    
    @Column(name="Actief", nullable=false)
    public boolean isActief() {
        return this.actief;
    }
    
    public void setActief(boolean actief) {
        this.actief = actief;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="supportReden")
    public Set<Support> getSupports() {
        return this.supports;
    }
    
    public void setSupports(Set<Support> supports) {
        this.supports = supports;
    }





}


