package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * SupportBestand generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="SupportBestand")
@Table(name="SupportBestand"
)
public class SupportBestand  implements java.io.Serializable {


     private Integer supportBestandId;
     private Support support;
     private String oorspronkelijkBestandsNaam;
     private Date datumUpload;
     private boolean gearchiveerd;
     private String volledigPad;
     private String referentieNummer;

    public SupportBestand() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SupportBestand_ID", unique=true, nullable=false)
    public Integer getSupportBestandId() {
        return this.supportBestandId;
    }
    
    public void setSupportBestandId(Integer supportBestandId) {
        this.supportBestandId = supportBestandId;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Support_ID", nullable=false)
    public Support getSupport() {
        return this.support;
    }
    
    public void setSupport(Support support) {
        this.support = support;
    }



    @Transient
    public Integer getSupportSupportId() {
        return this.support == null ? null : this.support.getSupportId();
    }

    public void setSupportSupportId(Integer supportId) {
        if (supportId == null) {
            this.support = null;
        } else {
            Support obj = new Support();
            obj.setSupportId(supportId);
            this.support = obj;
        }
    }


    
    @Column(name="OorspronkelijkBestandsNaam", nullable=false, length=100)
    public String getOorspronkelijkBestandsNaam() {
        return this.oorspronkelijkBestandsNaam;
    }
    
    public void setOorspronkelijkBestandsNaam(String oorspronkelijkBestandsNaam) {
        this.oorspronkelijkBestandsNaam = oorspronkelijkBestandsNaam;
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DatumUpload", nullable=false, length=19)
    public Date getDatumUpload() {
        return this.datumUpload;
    }
    
    public void setDatumUpload(Date datumUpload) {
        this.datumUpload = datumUpload;
    }


    
    @Column(name="Gearchiveerd", nullable=false)
    public boolean isGearchiveerd() {
        return this.gearchiveerd;
    }
    
    public void setGearchiveerd(boolean gearchiveerd) {
        this.gearchiveerd = gearchiveerd;
    }


    
    @Column(name="VolledigPad", nullable=false, length=100)
    public String getVolledigPad() {
        return this.volledigPad;
    }
    
    public void setVolledigPad(String volledigPad) {
        this.volledigPad = volledigPad;
    }


    
    @Column(name="ReferentieNummer", nullable=false, length=50)
    public String getReferentieNummer() {
        return this.referentieNummer;
    }
    
    public void setReferentieNummer(String referentieNummer) {
        this.referentieNummer = referentieNummer;
    }





}


