package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * Tarief generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="Tarief")
@Table(name="Tarief"
)
public class Tarief  implements java.io.Serializable {


     private Integer tariefId;
     private Product product;
     private Date geldigVanaf;
     private boolean actief;
     private Short dagenTrial;
     private BigDecimal bedrag;

    public Tarief() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Tarief_ID", unique=true, nullable=false)
    public Integer getTariefId() {
        return this.tariefId;
    }
    
    public void setTariefId(Integer tariefId) {
        this.tariefId = tariefId;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Product", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }



    @Transient
    public String getProductCode() {
        return this.product == null ? null : this.product.getCode();
    }

    public void setProductCode(String code) {
        if (code == null) {
            this.product = null;
        } else {
            Product obj = new Product();
            obj.setCode(code);
            this.product = obj;
        }
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.DATE)
    @Column(name="GeldigVanaf", nullable=false, length=10)
    public Date getGeldigVanaf() {
        return this.geldigVanaf;
    }
    
    public void setGeldigVanaf(Date geldigVanaf) {
        this.geldigVanaf = geldigVanaf;
    }


    
    @Column(name="Actief", nullable=false)
    public boolean isActief() {
        return this.actief;
    }
    
    public void setActief(boolean actief) {
        this.actief = actief;
    }


    
    @Column(name="DagenTrial")
    public Short getDagenTrial() {
        return this.dagenTrial;
    }
    
    public void setDagenTrial(Short dagenTrial) {
        this.dagenTrial = dagenTrial;
    }


    
    @Column(name="Bedrag", precision=10)
    public BigDecimal getBedrag() {
        return this.bedrag;
    }
    
    public void setBedrag(BigDecimal bedrag) {
        this.bedrag = bedrag;
    }





}


