package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * Wachtwoord generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="Wachtwoord")
@Table(name="Wachtwoord"
)
public class Wachtwoord  implements java.io.Serializable {


     private Integer wachtwoordId;
     private WachtwoordStatus wachtwoordStatus;
     private Date datumLaatsteWijziging;
     private String wachtwoord;
     private String wachtwoordOud1;
     private String wachtwoordOud2;
     private String wachtwoordOud3;
     private String wachtwoordOud4;
     private String activatieCode;
     private boolean forgotPasswordEmailSent;
     private Set<Gebruiker> gebruikers = new HashSet<Gebruiker>(0);

    public Wachtwoord() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Wachtwoord_ID", unique=true, nullable=false)
    public Integer getWachtwoordId() {
        return this.wachtwoordId;
    }
    
    public void setWachtwoordId(Integer wachtwoordId) {
        this.wachtwoordId = wachtwoordId;
    }


@XmlTransient
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WachtwoordStatus", nullable=false)
    public WachtwoordStatus getWachtwoordStatus() {
        return this.wachtwoordStatus;
    }
    
    public void setWachtwoordStatus(WachtwoordStatus wachtwoordStatus) {
        this.wachtwoordStatus = wachtwoordStatus;
    }



    @Transient
    public String getWachtwoordStatusCode() {
        return this.wachtwoordStatus == null ? null : this.wachtwoordStatus.getCode();
    }

    public void setWachtwoordStatusCode(String code) {
        if (code == null) {
            this.wachtwoordStatus = null;
        } else {
            WachtwoordStatus obj = new WachtwoordStatus();
            obj.setCode(code);
            this.wachtwoordStatus = obj;
        }
    }


// @org.codehaus.jackson.map.annotate.JsonSerialize(using=nl.devoorkant.bdr.jackson.JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DatumLaatsteWijziging", length=19)
    public Date getDatumLaatsteWijziging() {
        return this.datumLaatsteWijziging;
    }
    
    public void setDatumLaatsteWijziging(Date datumLaatsteWijziging) {
        this.datumLaatsteWijziging = datumLaatsteWijziging;
    }


    
    @Column(name="Wachtwoord", length=100)
    public String getWachtwoord() {
        return this.wachtwoord;
    }
    
    public void setWachtwoord(String wachtwoord) {
        this.wachtwoord = wachtwoord;
    }


    
    @Column(name="WachtwoordOud1", length=100)
    public String getWachtwoordOud1() {
        return this.wachtwoordOud1;
    }
    
    public void setWachtwoordOud1(String wachtwoordOud1) {
        this.wachtwoordOud1 = wachtwoordOud1;
    }


    
    @Column(name="WachtwoordOud2", length=100)
    public String getWachtwoordOud2() {
        return this.wachtwoordOud2;
    }
    
    public void setWachtwoordOud2(String wachtwoordOud2) {
        this.wachtwoordOud2 = wachtwoordOud2;
    }


    
    @Column(name="WachtwoordOud3", length=100)
    public String getWachtwoordOud3() {
        return this.wachtwoordOud3;
    }
    
    public void setWachtwoordOud3(String wachtwoordOud3) {
        this.wachtwoordOud3 = wachtwoordOud3;
    }


    
    @Column(name="WachtwoordOud4", length=100)
    public String getWachtwoordOud4() {
        return this.wachtwoordOud4;
    }
    
    public void setWachtwoordOud4(String wachtwoordOud4) {
        this.wachtwoordOud4 = wachtwoordOud4;
    }


    
    @Column(name="ActivatieCode", length=36)
    public String getActivatieCode() {
        return this.activatieCode;
    }
    
    public void setActivatieCode(String activatieCode) {
        this.activatieCode = activatieCode;
    }


    
    @Column(name="ForgotPasswordEmailSent", nullable=false)
    public boolean isForgotPasswordEmailSent() {
        return this.forgotPasswordEmailSent;
    }
    
    public void setForgotPasswordEmailSent(boolean forgotPasswordEmailSent) {
        this.forgotPasswordEmailSent = forgotPasswordEmailSent;
    }


@XmlTransient
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="wachtwoord")
    public Set<Gebruiker> getGebruikers() {
        return this.gebruikers;
    }
    
    public void setGebruikers(Set<Gebruiker> gebruikers) {
        this.gebruikers = gebruikers;
    }





}


