package nl.devoorkant.sbdr.data.model;
// Generated Feb 27, 2017 3:05:41 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * Websiteparam generated by hbm2java
 */

@XmlRootElement
// @org.jboss.resteasy.annotations.providers.jaxb.IgnoreMediaTypes("application/*+json")
// @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name="Websiteparam")
@Table(name="Websiteparam"
)
public class Websiteparam  implements java.io.Serializable {


     private Integer websiteparamId;
     private String storingen;
     private Integer startupsYtd;
     private Integer startupsWeek;
     private Integer vermeldingenYtd;
     private Integer vermeldingenWeek;

    public Websiteparam() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Websiteparam_ID", unique=true, nullable=false)
    public Integer getWebsiteparamId() {
        return this.websiteparamId;
    }
    
    public void setWebsiteparamId(Integer websiteparamId) {
        this.websiteparamId = websiteparamId;
    }


    
    @Column(name="Storingen", length=1000)
    public String getStoringen() {
        return this.storingen;
    }
    
    public void setStoringen(String storingen) {
        this.storingen = storingen;
    }


    
    @Column(name="StartupsYtd", precision=6, scale=0)
    public Integer getStartupsYtd() {
        return this.startupsYtd;
    }
    
    public void setStartupsYtd(Integer startupsYtd) {
        this.startupsYtd = startupsYtd;
    }


    
    @Column(name="StartupsWeek", precision=6, scale=0)
    public Integer getStartupsWeek() {
        return this.startupsWeek;
    }
    
    public void setStartupsWeek(Integer startupsWeek) {
        this.startupsWeek = startupsWeek;
    }


    
    @Column(name="VermeldingenYtd", precision=6, scale=0)
    public Integer getVermeldingenYtd() {
        return this.vermeldingenYtd;
    }
    
    public void setVermeldingenYtd(Integer vermeldingenYtd) {
        this.vermeldingenYtd = vermeldingenYtd;
    }


    
    @Column(name="VermeldingenWeek", precision=6, scale=0)
    public Integer getVermeldingenWeek() {
        return this.vermeldingenWeek;
    }
    
    public void setVermeldingenWeek(Integer vermeldingenWeek) {
        this.vermeldingenWeek = vermeldingenWeek;
    }





}


